"""JSON page descriptions -> .layout text, one engine idiom per primitive.

Spec: the UI layout generator design of 2026-09-04, §3.
The engine lays out lists, stacks, rows of self-sized labels and wrapped
text by itself (measured 2026-09-04, skill gui-layouts.md §24). What it
cannot do -- a `fill` in a column, a flexible column in a row, the width of
a row under a scrollbar -- is computed here ONCE, from the exact size of
the nearest exact ancestor. Nothing proportional is ever written with a
magnitude above 1, and every primitive writes the same idiom every time.
"""
from __future__ import annotations

import json
import sys
from dataclasses import dataclass, field
from pathlib import Path

from .profile import UI_DIR, TOKENS_FILE, resolve_mod_dir

#: A proportional-width child of a ScrollWidget with "Scrollbar V" 1 gets
#: the scroll's width minus this many layout units (measured 2026-09-04).
SCROLLBAR_UNITS = 10
#: First line of every generated file; mod_lint's layout-stale rule keys on it.
GENERATED_MARK = "// GENERATED by dayz-mcp layout_build from "
#: An ItemPreviewWidget under a priority above this draws nothing (measured).
PREVIEW_PRIORITY_MAX = 256
FONT_FACE_DEFAULT = "gui/fonts/sdf_MetronBook24"
PANEL_STYLE = "rover_sim_colorable"
#: Where a mod keeps its layouts, under the mod's source folder.
LAYOUT_DIR = "gui/layouts"
# UI_DIR/TOKENS_FILE (a project's descriptions: <root>/ui/tokens.json,
# <root>/ui/<Mod>/*.json) live in profile.py, not here -- BuildCfg.tokens'
# own default is built from the exact same two constants, so the default
# tokens path can never split between the two files by editing only one.


class LayoutGenError(ValueError):
    """A description the generator refuses: the file, the node and why."""

    def __init__(self, message: str, file: str = "", node: str = ""):
        super().__init__(message)
        self.message = message
        self.file = file
        self.node = node

    def __str__(self) -> str:
        where = " ".join(p for p in (self.file, self.node) if p)
        return f"{where}: {self.message}" if where else self.message


def fmt(value: float) -> str:
    """A number the way vanilla layouts write it: integers bare, floats to 3 places."""
    if isinstance(value, bool):
        raise TypeError("a bool is not a layout number")
    value = float(value)
    if value.is_integer():
        return str(int(value))
    return f"{value:.3f}".rstrip("0").rstrip(".")


def _is_number(value) -> bool:
    return isinstance(value, (int, float)) and not isinstance(value, bool)


def _is_pair(value) -> bool:
    return isinstance(value, list) and len(value) == 2 and all(_is_number(v) for v in value)


@dataclass
class Tokens:
    """The tokens file (`ui/tokens.json` by default, `build.tokens` to move
    it): the numbers, colours and fonts written once.

    `device` is the one group with no fixed shape of its own: an entry may
    be a pair (`[w, h]`, e.g. a screen size), a scalar (a plain number, e.g.
    a rail width) or a string (e.g. `iconset`, an imageset name) -- the
    caller's own reader (`number()`, `pair()`, `_iconset`) is what decides
    which shape it expects."""

    color: dict[str, list[float]] = field(default_factory=dict)
    font: dict[str, dict] = field(default_factory=dict)
    space: dict[str, float] = field(default_factory=dict)
    size: dict[str, float] = field(default_factory=dict)
    device: dict = field(default_factory=dict)
    file: str = "ui/tokens.json"

    @classmethod
    def from_text(cls, text: str, file: str = "ui/tokens.json") -> "Tokens":
        try:
            data = json.loads(text)
        except json.JSONDecodeError as exc:
            raise LayoutGenError(f"tokens do not parse: {exc}", file) from None
        if not isinstance(data, dict):
            raise LayoutGenError("tokens must be a JSON object", file)
        t = cls(file=file)
        for name, rgba in dict(data.get("color") or {}).items():
            good = (isinstance(rgba, list) and len(rgba) == 4
                    and all(_is_number(v) and 0 <= v <= 1 for v in rgba))
            if not good:
                raise LayoutGenError(f"color.{name} must be four numbers 0..1", file)
            t.color[name] = [float(v) for v in rgba]
        for name, spec in dict(data.get("font") or {}).items():
            good = (isinstance(spec, dict) and _is_number(spec.get("size"))
                    and isinstance(spec.get("face", FONT_FACE_DEFAULT), str)
                    and isinstance(spec.get("fixed", False), bool))
            if not good:
                raise LayoutGenError(f'font.{name} must be {{"face": str, "size": number, "fixed": bool}}', file)
            t.font[name] = {"face": spec.get("face", FONT_FACE_DEFAULT),
                            "size": float(spec["size"]), "fixed": bool(spec.get("fixed", False))}
        for group in ("space", "size"):
            for name, value in dict(data.get(group) or {}).items():
                if not _is_number(value):
                    raise LayoutGenError(f"{group}.{name} must be a number", file)
                getattr(t, group)[name] = float(value)
        t.device = dict(data.get("device") or {})
        return t

    @classmethod
    def load(cls, path: Path, label: str = "") -> "Tokens":
        """`from_text`, read off disk. `label` (default: `path` itself) is
        what every error this can raise names -- the caller's choice, so a
        tokens file inside the project reads `ui/tokens.json ...` rather
        than the machine's own absolute path to it. A general classmethod:
        the message only names the path, not WHY a project should have one
        -- `build_project`, its one caller today, already knows a `ui/<Mod>/`
        exists by the time it calls this, and says so itself."""
        label = label or str(path)
        if not path.is_file():
            raise LayoutGenError(f"{label} is missing", label)
        return cls.from_text(path.read_text(encoding="utf-8"), label)

    def number(self, value, file: str, node: str, what: str = "size") -> float:
        """A number, or a `$space.<name>` / `$size.<name>` / `$device.<name>` reference.

        `device` is not a table of plain floats like `space`/`size` -- a
        `device` name can name either shape (`pair()` reads the other one) --
        so a name found there that turns out to be a `[w, h]` pair is refused
        by its OWN name, the same way `pair()` refuses a scalar below."""
        if isinstance(value, bool):
            raise LayoutGenError(f"{what} must be a number, not a bool", file, node)
        if _is_number(value):
            return float(value)
        if isinstance(value, str) and value.startswith("$"):
            group, _, name = value[1:].partition(".")
            if group == "device":
                if name not in self.device:
                    raise LayoutGenError(f"unknown token {value!r} for {what}", file, node)
                got = self.device[name]
                if _is_number(got):
                    return float(got)
                if _is_pair(got):
                    raise LayoutGenError(f"{value!r} is a pair, not a number", file, node)
                raise LayoutGenError(f"{value!r} is not a number", file, node)
            table = {"space": self.space, "size": self.size}.get(group)
            if table is None or name not in table:
                raise LayoutGenError(f"unknown token {value!r} for {what}", file, node)
            return table[name]
        raise LayoutGenError(f"{what} must be a number or a $space/$size/$device token, got {value!r}", file, node)

    def pair(self, value, file: str, node: str, what: str = "size") -> tuple[float, float]:
        """`[w, h]` of numbers or tokens, or `$device.<name>` naming a two-number token."""
        if isinstance(value, str) and value.startswith("$device."):
            got = self.device.get(value[len("$device."):])
            if _is_number(got):
                raise LayoutGenError(f"{value!r} is a number, not a pair", file, node)
            if not _is_pair(got):
                raise LayoutGenError(f"{value!r} is not a [w, h] device token", file, node)
            return float(got[0]), float(got[1])
        if isinstance(value, list) and len(value) == 2:
            return (self.number(value[0], file, node, what + "[0]"),
                    self.number(value[1], file, node, what + "[1]"))
        raise LayoutGenError(f"{what} must be [w, h] or a $device token, got {value!r}", file, node)

    def color_of(self, value, file: str, node: str) -> tuple[list[float], bool]:
        """`(rgba, from_token)`: `$name` looks the colour up; a literal list passes and is reported."""
        if isinstance(value, str) and value.startswith("$"):
            name = value[1:]
            if name.startswith("color."):
                name = name[len("color."):]
            if name not in self.color:
                raise LayoutGenError(f"unknown color token {value!r}", file, node)
            return list(self.color[name]), True
        if isinstance(value, list) and len(value) == 4 and all(_is_number(v) for v in value):
            return [float(v) for v in value], False
        raise LayoutGenError(f"color must be a $token or four numbers, got {value!r}", file, node)

    def font_of(self, value, file: str, node: str) -> tuple[dict, bool]:
        """`(font, from_token)`: a token name (`header`, `$font.header`) or a literal spec."""
        if isinstance(value, str):
            name = value[1:] if value.startswith("$") else value
            if name.startswith("font."):
                name = name[len("font."):]
            if name in self.font:
                return dict(self.font[name]), True
            raise LayoutGenError(f"unknown font token {value!r}", file, node)
        if isinstance(value, dict) and _is_number(value.get("size")):
            return {"face": value.get("face", FONT_FACE_DEFAULT), "size": float(value["size"]),
                    "fixed": bool(value.get("fixed", False))}, False
        raise LayoutGenError(f'font must be a token name or {{"face", "size"}}, got {value!r}', file, node)


@dataclass
class W:
    """One widget to write: class, name, ordered properties, children."""

    cls: str
    name: str
    props: list[tuple[str, str]] = field(default_factory=list)
    children: list["W"] = field(default_factory=list)
    comment: str = ""

    def set(self, key: str, value: str) -> "W":
        for i, (k, _v) in enumerate(self.props):
            if k == key:
                self.props[i] = (key, value)
                return self
        self.props.append((key, value))
        return self


def quoted(text: str) -> str:
    return '"' + text + '"'


def key(name: str) -> str:
    """A property key as the engine wants it: quoted when it has spaces."""
    return quoted(name) if " " in name else name


def color_prop(rgba: list[float]) -> str:
    return " ".join(fmt(v) for v in rgba)


def render(w: W, indent: int = 0) -> str:
    pad = " " * indent
    lines = [f"{pad}// {c}".rstrip() for c in w.comment.splitlines()]
    lines.append(f"{pad}{w.cls} {w.name} {{")
    lines += [f"{pad} {k} {v}" for k, v in w.props]
    if w.children:
        lines.append(f"{pad} {{")
        lines += [render(c, indent + 2) for c in w.children]
        lines.append(f"{pad} }}")
    lines.append(f"{pad}}}")
    return "\n".join(lines)


ANCHORS = {"right": ("right_ref", None), "bottom": (None, "bottom_ref"),
           "center": ("center_ref", "center_ref"), "bottom-right": ("right_ref", "bottom_ref"),
           "bottom-center": ("center_ref", "bottom_ref")}


def place(w: W, x: float, y: float, width: float, height: float,
          hexact: bool = True, vexact: bool = True, anchor: str = "") -> W:
    """Position and size, exact unless told otherwise; an anchor moves the reference edge."""
    ha, va = ANCHORS.get(anchor, (None, None))
    if ha:
        w.set("halign", ha)
    if va:
        w.set("valign", va)
    w.set("position", f"{fmt(x)} {fmt(y)}")
    w.set("size", f"{fmt(width)} {fmt(height)}")
    w.set("hexactpos", "1")
    w.set("vexactpos", "1")
    w.set("hexactsize", "1" if hexact else "0")
    w.set("vexactsize", "1" if vexact else "0")
    return w


@dataclass
class Box:
    """What a child may occupy: the parent's inner size and where that inner
    area starts (`ox`/`oy`, a frame's inset -- positions are written relative
    to the parent WIDGET, so a child at the inner origin sits at `ox oy`).
    `w`/`h` None = not known here (an engine container decides); `prop_w` =
    the parent's width is the engine's to decide (a row under a scrollbar),
    so a full-width child is `size 1`."""

    w: float | None
    h: float | None
    prop_w: bool = False
    ox: float = 0.0
    oy: float = 0.0
    #: children are laid out by the engine: every child must be one widget
    engine: bool = False


@dataclass
class Ctx:
    tokens: Tokens
    file: str
    layout_dir: str
    notes: list[str] = field(default_factory=list)
    files: dict[str, str] = field(default_factory=dict)
    names: set[str] = field(default_factory=set)
    gaps: int = 0
    hrows: int = 0
    chain: list[int] = field(default_factory=list)

    def claim(self, name, path: str) -> str:
        if not isinstance(name, str) or not name:
            raise LayoutGenError("a widget needs a name (a non-empty string)", self.file, path)
        if name in self.names:
            raise LayoutGenError(f"duplicate widget name {name!r} in this file", self.file, path)
        self.names.add(name)
        return name

    def gap_name(self, path: str) -> str:
        self.gaps += 1
        return self.claim(f"Gap{self.gaps}", path)

    def hrow_name(self, path: str) -> str:
        """The next anonymous hrow's name. A COUNTER, not a count of the
        names already claimed: counting made an unrelated widget called
        `HRowFoo` renumber every anonymous row after it."""
        self.hrows += 1
        return self.claim(f"HRow{self.hrows}", path)

    def fresh(self) -> "Ctx":
        """A context for another FILE of the same build: names start over,
        notes and files are shared."""
        return Ctx(self.tokens, self.file, self.layout_dir, self.notes, self.files)

    def note(self, path: str, text: str) -> None:
        self.notes.append(f"{self.file} {path}: {text}")


@dataclass
class Emitted:
    """What one description makes: `files` maps a project-relative path
    (`<Mod>/gui/layouts/<name>.layout`) to its text."""

    files: dict[str, str]
    notes: list[str]


COMMON = {"name", "note", "hidden", "priority", "anchor", "at", "w", "h", "size", "color"}
ALLOWED: dict[str, set[str]] = {
    "frame":   COMMON | {"inset", "children"},
    "panel":   COMMON | {"edge", "click", "inset", "children"},
    "vbox":    COMMON | {"gap", "children"},
    "hbox":    COMMON | {"gap", "children"},
    "stack":   COMMON | {"children"},
    "hrow":    COMMON | {"children"},
    # No "row": a row template is not a node of a page, it is the value of a
    # list's `rows` and its attributes are ROW_ATTRS. Listed here it was a
    # second, disagreeing schema for one key -- it admitted `at`/`anchor`,
    # which _build_row rejects, and omitted `click`/`stack`, which it needs.
    "grid":    COMMON | {"cols", "rows", "gap", "children"},
    "list":    COMMON | {"stack", "rows", "children"},
    "keypad":  COMMON | {"cols", "rows", "gap", "keys", "font"},
    "label":   COMMON | {"text", "font", "align", "valign"},
    "text":    COMMON | {"text", "font", "align", "plain", "grow"},
    "field":   COMMON | {"text", "font", "lines"},
    # "children" is a root-only capability (a button root holds page
    # content the way a frame/panel root does) -- a plain child button
    # still gets its Edge/Bg/Text idiom from `_b_button`, which never reads it.
    "button":  COMMON | {"text", "font", "bg", "edge", "glyph", "children"},
    "rule":    COMMON,
    "bar":     (COMMON - {"color"}) | {"track", "fill"},   # a bar is coloured by track/fill
    "gap":     COMMON,
    "chip":    COMMON,
    "section": COMMON | {"text", "font"},
    "icon":    COMMON | {"set", "image"},
    "image":   COMMON | {"file", "stretch", "props"},
    "badge":   COMMON | {"font"},
    # No "color": nothing under any project's `ui/` puts one directly on a
    # header (grepped 2026-09-04) -- only ever inside `title`, where
    # `_b_header` already reaches the title label with it. COMMON grants it
    # like every primitive, but `_stackbox`'s own `row` never reads it, so a
    # header carrying one had it silently dropped, no note.
    "header":  (COMMON - {"color"}) | {"icon", "title", "actions", "gap", "font"},
    "listbox": COMMON | {"font", "props"},
    "preview": COMMON | {"props"},
    "raw":     COMMON | {"class", "props", "children"},
    # "children" is granted, not read: `_b_map` refuses it itself, by name
    # (gui-layouts.md §19 -- a map paints over its children, not just under
    # them), the same way `button` grants it to give its own note instead of
    # the generic "map does not take ['children']".
    "map":     COMMON | {"children"},
}
ROOT_KINDS = ("frame", "panel", "button")


def _unpack(desc, file: str, path: str) -> tuple[str, dict]:
    if not isinstance(desc, dict) or len(desc) != 1:
        raise LayoutGenError("a node is an object with exactly one primitive key", file, path)
    (kind, attrs), = desc.items()
    if kind not in ALLOWED:
        raise LayoutGenError(f"unknown primitive {kind!r}; known: {', '.join(sorted(ALLOWED))}", file, path)
    if not isinstance(attrs, dict):
        raise LayoutGenError(f"{kind} must hold an object of attributes", file, path)
    extra = sorted(set(attrs) - ALLOWED[kind])
    if extra:
        raise LayoutGenError(f"{kind} does not take {extra}", file, path)
    return kind, attrs


def _priority(attrs: dict, ctx: Ctx, path: str, index: int) -> int:
    if "priority" not in attrs:
        return index
    return int(ctx.tokens.number(attrs["priority"], ctx.file, path, "priority"))


def _text_value(attrs: dict, ctx: Ctx, path: str) -> str:
    text = str(attrs.get("text", ""))
    if '"' in text:
        raise LayoutGenError("a quote inside text hangs the engine's layout parser", ctx.file, path)
    return text


def _dim(attrs: dict, which: str, ctx: Ctx, path: str, avail: float | None, default,
         allow_auto: bool = False):
    """One of w/h: a number, a token, "fill" (= `avail`), "auto" (a label's
    width) or `default`. `size: [w, h]` / `size: "fill"` stands for both."""
    value = attrs.get(which, default)
    if "size" in attrs:
        if "w" in attrs or "h" in attrs:
            raise LayoutGenError("size and w/h on one node -- use one", ctx.file, path)
        size = attrs["size"]
        if size == "fill":
            value = "fill"
        else:
            pair = ctx.tokens.pair(size, ctx.file, path)
            value = pair[0 if which == "w" else 1]
    if value is None:
        raise LayoutGenError(f"{which} is required here", ctx.file, path)
    if value == "fill":
        if avail is None:
            raise LayoutGenError(f"{which}: fill needs an exact ancestor to fill", ctx.file, path)
        return float(avail)
    if value == "auto":
        if not allow_auto:
            raise LayoutGenError("auto is only a label's width", ctx.file, path)
        return "auto"
    return ctx.tokens.number(value, ctx.file, path, which)


def _avail(side: float | None, inset: float) -> float | None:
    """How much of a box a child `inset` units in can fill (from the left or
    top for a plain child, from the edge it hangs off for an anchored one)."""
    if side is None:
        return None
    return side - inset


def _size_leaf(attrs: dict, ctx: Ctx, box: Box, path: str, x: float, y: float, forced: tuple,
               anchor: str, default_h, allow_auto: bool = False, exact_only: bool = False) -> tuple:
    """The (width, height, hexactsize, vexactsize) of one leaf.

    Two shortcuts stand in for arithmetic the engine does better, and
    `exact_only` (a container that must know its own numbers: vbox, grid,
    button, field, list) turns both off:

    * `size: "fill"` at an uninset origin is the parent's whole box, written
      `size 1 1` proportional -- no number to go stale when the parent moves;
    * an undeclared width inside a PROPORTIONAL parent (`box.prop_w`: a list
      row, whose width the engine sets from the scroll minus its bar) is
      `size 1 h`, hexactsize 0, for the same reason.

    Otherwise the size is exact: what the node declares, or the remainder of
    the box from where the node sits (`_avail`). `forced` is the axis a
    vbox/hbox has already decided, and it wins over both the declaration and
    the shortcuts. A label's `w: "auto"` returns width 0 -- the engine sizes
    it from its own text.
    """
    inset_x = x - box.ox
    inset_y = y - box.oy
    full = (attrs.get("size") == "fill" and "w" not in attrs and "h" not in attrs
            and x == 0 and y == 0 and box.ox == 0 and box.oy == 0
            and not anchor and forced == (None, None) and not exact_only)
    if full:
        return 1.0, 1.0, False, False
    w = forced[0] if forced[0] is not None else _dim(attrs, "w", ctx, path, _avail(box.w, inset_x), "fill", allow_auto)
    h = forced[1] if forced[1] is not None else _dim(attrs, "h", ctx, path, _avail(box.h, inset_y), default_h)
    hexact = True
    declared_w = "w" in attrs or "size" in attrs or forced[0] is not None
    if w != "auto" and box.prop_w and inset_x == 0 and not anchor and not declared_w and not exact_only:
        w, hexact = 1.0, False
    if w == "auto":
        return 0.0, h, True, True
    return w, h, hexact, True


def _common_leaf(cls: str, attrs: dict, ctx: Ctx, path: str, ignore: bool = True) -> W:
    w = W(cls, ctx.claim(attrs.get("name", ""), path), comment=str(attrs.get("note", "")))
    w.set("visible", "0" if attrs.get("hidden") else "1")
    if ignore:
        w.set("ignorepointer", "1")
    return w


def _color(w: W, attrs: dict, ctx: Ctx, path: str, default: str, attr: str = "color") -> W:
    """Read `attrs[attr]` (a `$token` or a literal) and write it as `color`
    on the widget. `attr` differs from `"color"` only for `bar`, whose one
    node carries two colours (`track`/`fill`) -- each read and noted the
    same way every other primitive's single `color` is."""
    rgba, from_token = ctx.tokens.color_of(attrs.get(attr, default), ctx.file, path)
    if not from_token:
        ctx.note(path, f"{attr} given as a literal -- use a $color token")
    return w.set("color", color_prop(rgba))


def _text_font(w: W, attrs: dict, ctx: Ctx, path: str, default: str) -> dict:
    font, from_token = ctx.tokens.font_of(attrs.get("font", default), ctx.file, path)
    if not from_token:
        ctx.note(path, "font given as a literal -- use a $font token")
    w.set("text", quoted(_text_value(attrs, ctx, path)))
    w.set("font", quoted(font["face"]))
    w.set(key("exact text"), "1")
    if not font["fixed"]:
        w.set(key("exact text size"), fmt(font["size"]))
    return font


def _children(attrs: dict, ctx: Ctx, box: Box, path: str) -> list[W]:
    out: list[W] = []
    for i, child in enumerate(attrs.get("children", [])):
        out += emit(child, ctx, box, f"{path}.{i}", i)
    return out


def emit(desc, ctx: Ctx, box: Box, path: str, index: int, placed: tuple | None = None,
         on_page: bool = False) -> list[W]:
    """One description node -> the widgets it stands for (a nameless
    vbox/hbox returns its children flattened, everything else one widget).

    `placed` = (x, y, w, h) decided by a vbox/hbox (w or h None = as the
    node declares); without it the node places itself with `at` (default
    0 0, offset by the box's inset) and `anchor`. `on_page` marks a direct
    child of a frame/panel page root, where a visible `at` is noted: pages
    are built with containers, not coordinates. False for a button root's
    children -- a button root is a fixed-size compound control, not a page.
    """
    kind, attrs = _unpack(desc, ctx.file, path)
    anchor = attrs.get("anchor", "")
    if anchor and anchor not in ANCHORS:
        raise LayoutGenError(f"unknown anchor {anchor!r}; one of {sorted(ANCHORS)}", ctx.file, path)
    if placed is None:
        ax, ay = ctx.tokens.pair(attrs.get("at", [0, 0]), ctx.file, path, "at")
        x = ax if anchor in ("center", "bottom-center") else ax + box.ox
        y = ay if anchor == "center" else ay + box.oy
        forced = (None, None)
        if on_page and "at" in attrs and not attrs.get("hidden"):
            ctx.note(path, "`at` on a page child -- build the page with vbox/hbox")
    else:
        if "at" in attrs:
            raise LayoutGenError(f"{kind}: `at` is not allowed under a vbox/hbox -- the container places it", ctx.file, path)
        # An anchor is refused for the same reason `at` is, and it is the
        # worse of the two: it does not move the widget, it changes what the
        # coordinate the container computed MEANS (`bottom_ref` reads a
        # top-down offset as a bottom-up one), so the child lands far away
        # and the siblings do not follow.
        if anchor:
            raise LayoutGenError(f"{kind}: `anchor` is not allowed under a vbox/hbox -- the container places it", ctx.file, path)
        x, y, fw, fh = placed
        forced = (fw, fh)
    builder = BUILDERS.get(kind)
    if builder is None:
        raise LayoutGenError(f"{kind} is not implemented", ctx.file, path)
    priority = _priority(attrs, ctx, path, index)
    ctx.chain.append(priority)
    try:
        return builder(attrs, ctx, box, path, x, y, forced, anchor, priority)
    finally:
        ctx.chain.pop()


def _b_frame(attrs, ctx, box, path, x, y, forced, anchor, priority) -> list[W]:
    w = _common_leaf("FrameWidgetClass", attrs, ctx, path, ignore=False)
    width, height, hx, vx = _size_leaf(attrs, ctx, box, path, x, y, forced, anchor, None)
    place(w, x, y, width, height, hx, vx, anchor)
    w.set("priority", fmt(priority))
    inset = ctx.tokens.number(attrs.get("inset", 0), ctx.file, path, "inset")
    inner_w = _inset_extent(width, hx, box.w, inset, "width", ctx, path)
    inner_h = _inset_extent(height, vx, box.h, inset, "height", ctx, path)
    inner = Box(inner_w, inner_h, prop_w=not hx and not inset, ox=inset, oy=inset)
    w.children = _children(attrs, ctx, inner, path)
    return [w]


def _inset_extent(size: float, exact: bool, box_size: float | None, inset: float,
                  axis: str, ctx: Ctx, path: str) -> float | None:
    """One axis of the room a panel's or frame's children have inside its
    own `inset`.

    Exact (`size` is a real number -- this node's own hexactsize/vexactsize)
    is `size - 2 * inset`, same arithmetic as a frame's inner box. Proportional
    (the "full" shortcut: this node's own `size` is 1.0, not a usable number)
    instead needs what the node actually renders as -- `box_size`, the box IT
    was handed, which is a real number whenever the nearest ancestor that
    fixed it is exact (a frame/vbox of known size) even though this node's
    own line stays proportional. Without an inset there is nothing to
    subtract, so an unresolved `box_size` (still `None`, e.g. under a screen
    root) passes through unchanged, exactly as before; WITH one, subtracting
    from an unknown `box_size` would hand a fill child the un-reduced box and
    it would overflow past this node's true edge by `inset` -- refused
    instead of silently drawn wrong.
    """
    if exact:
        return size - 2 * inset
    if not inset:
        return box_size
    if box_size is None:
        raise LayoutGenError(f"a proportional panel or frame with an inset needs a known {axis} -- "
                             "give it w/h or drop the inset", ctx.file, path)
    return box_size - 2 * inset


def _b_panel(attrs, ctx, box, path, x, y, forced, anchor, priority) -> list[W]:
    w = _common_leaf("PanelWidgetClass", attrs, ctx, path, ignore=not attrs.get("click"))
    width, height, hx, vx = _size_leaf(attrs, ctx, box, path, x, y, forced, anchor, None)
    place(w, x, y, width, height, hx, vx, anchor)
    _color(w, attrs, ctx, path, "$panel")
    w.set("priority", fmt(priority)).set("style", PANEL_STYLE)
    out = []
    if attrs.get("edge"):
        if not (hx and vx):
            raise LayoutGenError("edge needs an exact size", ctx.file, path)
        edge = W("PanelWidgetClass", ctx.claim(w.name + "Edge", path))
        edge.set("visible", "0" if attrs.get("hidden") else "1").set("ignorepointer", "1")
        # A border one unit outside the panel on every side. `right_ref` and
        # `bottom_ref` measure INTO the parent from that edge, so a position
        # one unit smaller still moves the border outwards there, exactly as
        # it does for an unanchored top-left one. `center_ref` measures from
        # the middle: growing by 2 is the whole of it, and the -1 would push
        # the border off-centre, leaving a 2-unit border on two sides and
        # none on the other two (measured 2026-09-04).
        ha, va = ANCHORS.get(anchor, (None, None))
        ex = x if ha == "center_ref" else x - 1
        ey = y if va == "center_ref" else y - 1
        place(edge, ex, ey, width + 2, height + 2, anchor=anchor)
        rgba, _ = ctx.tokens.color_of("$edge", ctx.file, path)
        edge.set("color", color_prop(rgba)).set("priority", fmt(priority)).set("style", PANEL_STYLE)
        out.append(edge)
    inset = ctx.tokens.number(attrs.get("inset", 0), ctx.file, path, "inset")
    inner_w = _inset_extent(width, hx, box.w, inset, "width", ctx, path)
    inner_h = _inset_extent(height, vx, box.h, inset, "height", ctx, path)
    inner = Box(inner_w, inner_h, prop_w=not hx and not inset, ox=inset, oy=inset)
    w.children = _children(attrs, ctx, inner, path)
    return out + [w]


def _b_label(attrs, ctx, box, path, x, y, forced, anchor, priority) -> list[W]:
    w = _common_leaf("TextWidgetClass", attrs, ctx, path)
    font, _ = ctx.tokens.font_of(attrs.get("font", "body"), ctx.file, path)
    width, height, hx, vx = _size_leaf(attrs, ctx, box, path, x, y, forced, anchor,
                                       font["size"] + 9, allow_auto=True)
    place(w, x, y, width, height, hx, vx, anchor)
    _color(w, attrs, ctx, path, "$text")
    w.set("priority", fmt(priority))
    _text_font(w, attrs, ctx, path, "body")
    w.set(key("text halign"), str(attrs.get("align", "left")))
    w.set(key("text valign"), str(attrs.get("valign", "center")))
    if attrs.get("w") == "auto":
        w.set(key("size to text h"), "1")
    return [w]


def _b_rule(attrs, ctx, box, path, x, y, forced, anchor, priority) -> list[W]:
    w = _common_leaf("PanelWidgetClass", attrs, ctx, path)
    width, _h, hx, _vx = _size_leaf(attrs, ctx, box, path, x, y, (forced[0], 1.0), anchor, 1)
    place(w, x, y, width, 1, hx, True, anchor)
    _color(w, attrs, ctx, path, "$rule")
    return [w.set("priority", fmt(priority)).set("style", PANEL_STYLE)]


def _b_bar(attrs, ctx, box, path, x, y, forced, anchor, priority) -> list[W]:
    """A track holding one child, `<Name>Fill`: `position 0 0`, `size 0 h`
    -- an EMPTY bar. Widening it is the script's job at runtime
    (`bar.GetSize(w, h); fill.SetSize(w * value01, h)`); the generator never
    sees the fraction, only the height both panels share. `h` defaults to
    `$size.bar` -- here directly, and in `_default_main` for a vbox, which
    resolves a child's height before `_b_bar` ever sees it."""
    w = _common_leaf("PanelWidgetClass", attrs, ctx, path)
    width, height, hx, vx = _size_leaf(attrs, ctx, box, path, x, y, forced, anchor, "$size.bar")
    place(w, x, y, width, height, hx, vx, anchor)
    _color(w, attrs, ctx, path, "$rule", attr="track")
    w.set("priority", fmt(priority)).set("style", PANEL_STYLE)
    fill = W("PanelWidgetClass", ctx.claim(w.name + "Fill", path))
    fill.set("visible", "1").set("ignorepointer", "1")
    place(fill, 0, 0, 0, height)
    _color(fill, attrs, ctx, path, "$accent", attr="fill")
    fill.set("priority", "1").set("style", PANEL_STYLE)
    w.children = [fill]
    return [w]


def _b_chip(attrs, ctx, box, path, x, y, forced, anchor, priority) -> list[W]:
    """A 4-unit bar the full height of its parent, hidden until a script colours it."""
    w = W("PanelWidgetClass", ctx.claim(attrs.get("name", ""), path), comment=str(attrs.get("note", "")))
    w.set("visible", "0" if attrs.get("hidden", True) else "1").set("ignorepointer", "1")
    if "h" in attrs:
        ctx.note(path, "chip ignores h -- it is its parent's full height")
    width = ctx.tokens.number(attrs.get("w", 4), ctx.file, path, "w")
    place(w, x, y, width, 1, True, False, anchor)
    _color(w, attrs, ctx, path, "$white")
    return [w.set("priority", fmt(priority)).set("style", PANEL_STYLE)]


def _b_gap(attrs, ctx, box, path, x, y, forced, anchor, priority) -> list[W]:
    """An empty panel that holds space inside an ENGINE container (hrow/stack);
    inside vbox/hbox a gap is arithmetic and never reaches here. In a stack
    it takes the stack's width (`size 1 h` under a scrollbar), in an hrow
    it must say its `w`."""
    w = W("PanelWidgetClass", ctx.gap_name(path)).set("visible", "1").set("ignorepointer", "1")
    width, height, hx, vx = _size_leaf(attrs, ctx, box, path, x, y, forced, anchor, 0)
    place(w, x, y, width, height, hx, vx, anchor)
    rgba, _ = ctx.tokens.color_of("$none", ctx.file, path)
    return [w.set("color", color_prop(rgba)).set("priority", fmt(priority)).set("style", PANEL_STYLE)]


BUILDERS = {
    "frame": _b_frame, "panel": _b_panel, "label": _b_label,
    "rule": _b_rule, "bar": _b_bar, "chip": _b_chip, "gap": _b_gap,
}


def _declared(attrs: dict, which: str, ctx: Ctx, path: str):
    """The main-axis size a container child declares: a number, "fill" or None."""
    value = attrs.get(which)
    if "size" in attrs:
        size = attrs["size"]
        if size == "fill":
            return "fill"
        value = ctx.tokens.pair(size, ctx.file, path)[0 if which == "w" else 1]
    if value is None:
        return None
    if value == "fill":
        return "fill"
    if value == "auto":
        raise LayoutGenError("auto is only a label's width, and only inside an hrow", ctx.file, path)
    return ctx.tokens.number(value, ctx.file, path, which)


def _default_main(kind: str, attrs: dict, ctx: Ctx, path: str, vertical: bool) -> float:
    """What a child takes along a vbox/hbox's axis when it says nothing."""
    if vertical:
        if kind == "label":
            font, _ = ctx.tokens.font_of(attrs.get("font", "body"), ctx.file, path)
            return font["size"] + 9
        if kind == "button" and "button" in ctx.tokens.size:
            return ctx.tokens.size["button"]
        if kind == "field" and "field" in ctx.tokens.size:
            return ctx.tokens.size["field"]
        if kind == "rule":
            return 1.0
        if kind == "bar":
            return ctx.tokens.number("$size.bar", ctx.file, path, "h")
        if kind == "section":
            return 30.0
        if kind == "header":
            # The same default `_b_header` falls back to internally
            # (`row.setdefault`-style, via `"h" not in row`) when it is not
            # itself inside a vbox/hbox. Resolved here so a vbox can size
            # the row BEFORE dispatching to _b_header, which by then only
            # ever sees the forced height this returns (forced wins over
            # $size.header inside _b_header's own _stackbox call).
            return ctx.tokens.number("$size.header", ctx.file, path, "h")
        if kind == "text":
            raise LayoutGenError("text needs h inside a vbox (its height is the engine's only inside a stack)", ctx.file, path)
        raise LayoutGenError("h is required here", ctx.file, path)
    # No case for "header" here: a vbox's default is a ROW's height
    # ($size.header, one token), but an hbox's main axis is width, and no
    # single token stands for a header row's default width. So a header
    # inside an hbox keeps demanding an explicit w, same as every other
    # kind that falls through to this same line.
    raise LayoutGenError("w is required here", ctx.file, path)


def _stackbox(attrs, ctx, box, path, x, y, forced, anchor, priority, vertical: bool) -> list[W]:
    kind = "vbox" if vertical else "hbox"
    width, height, hx, vx = _size_leaf(attrs, ctx, box, path, x, y, forced, anchor, "fill", exact_only=True)
    if not (hx and vx):
        raise LayoutGenError(f"{kind} needs an exact size to lay children out in", ctx.file, path)
    gap = ctx.tokens.number(attrs.get("gap", 0), ctx.file, path, "gap")
    kids = list(attrs.get("children", []))
    main = height if vertical else width
    which = "h" if vertical else "w"
    sizes = []
    fills = []
    for i, kid in enumerate(kids):
        kkind, kattrs = _unpack(kid, ctx.file, f"{path}.{i}")
        value = _declared(kattrs, which, ctx, f"{path}.{i}")
        if value is None:
            value = _default_main(kkind, kattrs, ctx, f"{path}.{i}", vertical)
        if value == "fill":
            fills.append(i)
        sizes.append(value)
    used = sum(s for s in sizes if s != "fill") + gap * max(0, len(kids) - 1)
    if used > main + 0.001:
        raise LayoutGenError(f"{kind} does not fit: needs {fmt(used)}, has {fmt(main)}", ctx.file, path)
    if fills:
        # several fills share the remainder equally: two `fill` buttons in a
        # row are two equal buttons, whatever the row's width becomes
        each = (main - used) / len(fills)
        for i in fills:
            sizes[i] = each

    wrap = bool(attrs.get("name")) or box.engine
    if attrs.get("hidden") and not wrap:
        # Without a name (and outside an engine container, which always
        # wraps) a vbox/hbox never becomes its own widget: its children are
        # flattened straight into the parent, so there is no `visible` line
        # anywhere for `hidden` to set. COMMON grants it to every primitive
        # including this one, so silently rendering a fully visible
        # container would break that promise; `header` reaches this same
        # code (an unnamed row) whenever it has no name of its own.
        raise LayoutGenError("hidden needs a name -- a nameless container is not a widget", ctx.file, path)
    if wrap:
        frame = _common_leaf("FrameWidgetClass", attrs, ctx, path, ignore=False)
        place(frame, x, y, width, height, anchor=anchor)
        frame.set("priority", fmt(priority))
        inner = Box(width, height)
        base_x, base_y = 0.0, 0.0
    else:
        frame = None
        inner = Box(width, height, ox=x, oy=y)
        base_x, base_y = x, y
    out: list[W] = []
    cursor = 0.0
    for i, kid in enumerate(kids):
        kkind, kattrs = _unpack(kid, ctx.file, f"{path}.{i}")
        size = sizes[i]
        if kkind != "gap":
            # the cross axis is the container's unless the child says otherwise
            if vertical:
                own_w = "w" in kattrs or "size" in kattrs
                placed = (base_x, base_y + cursor, None if own_w else width, size)
            else:
                own_h = "h" in kattrs or "size" in kattrs
                cy = base_y
                if own_h:
                    declared_h = _declared(kattrs, "h", ctx, f"{path}.{i}")
                    if isinstance(declared_h, float) and declared_h < height:
                        cy = base_y + (height - declared_h) / 2
                placed = (base_x + cursor, cy, size, None if own_h else height)
            out += emit(kid, ctx, inner, f"{path}.{i}", i, placed=placed)
        cursor += size + gap
    if frame is not None:
        frame.children = out
        return [frame]
    return out


def _b_vbox(attrs, ctx, box, path, x, y, forced, anchor, priority) -> list[W]:
    return _stackbox(attrs, ctx, box, path, x, y, forced, anchor, priority, vertical=True)


def _b_hbox(attrs, ctx, box, path, x, y, forced, anchor, priority) -> list[W]:
    return _stackbox(attrs, ctx, box, path, x, y, forced, anchor, priority, vertical=False)


def _b_text(attrs, ctx, box, path, x, y, forced, anchor, priority) -> list[W]:
    cls = "MultilineTextWidgetClass" if attrs.get("plain") else "RichTextWidgetClass"
    w = _common_leaf(cls, attrs, ctx, path)
    width, height, hx, vx = _size_leaf(attrs, ctx, box, path, x, y, forced, anchor, 20)
    place(w, x, y, width, height, hx, vx, anchor)
    _color(w, attrs, ctx, path, "$text")
    w.set("priority", fmt(priority))
    _text_font(w, attrs, ctx, path, "body")
    w.set(key("text halign"), str(attrs.get("align", "left")))
    w.set(key("text valign"), "top")
    w.set("wrap", "1")
    w.set(key("size to text h"), "0")
    w.set(key("size to text v"), "1" if attrs.get("grow", True) else "0")
    return [w]


def _b_button(attrs, ctx, box, path, x, y, forced, anchor, priority) -> list[W]:
    """Button + Edge + Bg + Text children: the one button idiom that keeps
    its caption visible (vanilla button styles paint over children)."""
    name = ctx.claim(attrs.get("name", ""), path)
    btn = W("ButtonWidgetClass", name, comment=str(attrs.get("note", "")))
    btn.set("visible", "0" if attrs.get("hidden") else "1")
    if attrs.get("children"):
        ctx.note(path, "button ignores children outside the root")
    default_h = ctx.tokens.size.get("button", 30)
    width, height, hx, vx = _size_leaf(attrs, ctx, box, path, x, y, forced, anchor, default_h, exact_only=True)
    if not (hx and vx):
        raise LayoutGenError("button needs an exact size", ctx.file, path)
    place(btn, x, y, width, height, anchor=anchor)
    btn.set("text", quoted("")).set("priority", fmt(priority))
    kids: list[W] = []
    if attrs.get("edge", True):
        edge = W("PanelWidgetClass", ctx.claim(name + "Edge", path))
        edge.set("visible", "1").set("ignorepointer", "1")
        place(edge, -1, -1, width + 2, height + 2)
        rgba, _ = ctx.tokens.color_of(attrs["edge"] if isinstance(attrs.get("edge"), str) else "$edge", ctx.file, path)
        kids.append(edge.set("color", color_prop(rgba)).set("priority", "0").set("style", PANEL_STYLE))
    if attrs.get("bg", True):
        bg = W("PanelWidgetClass", ctx.claim(name + "Bg", path))
        bg.set("visible", "1").set("ignorepointer", "1")
        place(bg, 0, 0, width, height)
        rgba, _ = ctx.tokens.color_of(attrs["bg"] if isinstance(attrs.get("bg"), str) else "$raised", ctx.file, path)
        kids.append(bg.set("color", color_prop(rgba)).set("priority", "1").set("style", PANEL_STYLE))
    label = W("TextWidgetClass", ctx.claim(name + "Text", path))
    label.set("visible", "1").set("ignorepointer", "1")
    place(label, 0, 0, width, height)
    _color(label, attrs, ctx, path, "$accent")
    label.set("priority", "2")
    _text_font(label, attrs, ctx, path, "header" if attrs.get("glyph") else "small")
    label.set(key("text halign"), "center").set(key("text valign"), "center")
    kids.append(label)
    btn.children = kids
    return [btn]


def _b_field(attrs, ctx, box, path, x, y, forced, anchor, priority) -> list[W]:
    """An edit box that always has a box around it: <Name>Frame (edge colour)
    holding <Name>Fill (panel colour) and the EditBoxWidgetClass <Name>."""
    name = ctx.claim(attrs.get("name", ""), path)
    frame = W("PanelWidgetClass", ctx.claim(name + "Frame", path), comment=str(attrs.get("note", "")))
    frame.set("visible", "0" if attrs.get("hidden") else "1")
    default_h = ctx.tokens.size.get("field", 28)
    width, height, hx, vx = _size_leaf(attrs, ctx, box, path, x, y, forced, anchor, default_h, exact_only=True)
    if not (hx and vx):
        raise LayoutGenError("field needs an exact size", ctx.file, path)
    place(frame, x, y, width, height, anchor=anchor)
    rgba, _ = ctx.tokens.color_of("$edge", ctx.file, path)
    frame.set("color", color_prop(rgba)).set("priority", fmt(priority)).set("style", PANEL_STYLE)
    fill = W("PanelWidgetClass", ctx.claim(name + "Fill", path))
    fill.set("visible", "1").set("ignorepointer", "1")
    place(fill, 1, 1, width - 2, height - 2)
    rgba, _ = ctx.tokens.color_of("$panel", ctx.file, path)
    fill.set("color", color_prop(rgba)).set("priority", "0").set("style", PANEL_STYLE)
    lines = attrs.get("lines")
    edit = W("MultilineEditBoxWidgetClass" if lines else "EditBoxWidgetClass", name)
    edit.set("visible", "1")
    if lines:
        place(edit, 6, 4, width - 12, height - 8)
    else:
        place(edit, 6, 0, width - 12, height)
    _color(edit, attrs, ctx, path, "$text")
    edit.set("priority", "1").set("style", "Default")
    _text_font(edit, attrs, ctx, path, "field")
    if lines:
        edit.set("lines", fmt(ctx.tokens.number(lines, ctx.file, path, "lines")))
    frame.children = [fill, edit]
    return [frame]


def _b_section(attrs, ctx, box, path, x, y, forced, anchor, priority) -> list[W]:
    """A VPP-style section head: a frame <Name> holding <Name>Bar,
    <Name>Lbl and <Name>Rule at fixed offsets INSIDE it.

    The wrapper is what makes the head survive an anchor. As three anchored
    siblings the parts each measured from the anchored edge, so under
    `right` the bar landed 20 units from the right, the label's right edge
    32 units from it -- the label entirely to the LEFT of the bar it is
    supposed to follow -- and the rule spanned a different band again
    (measured 2026-09-04). Inside the wrapper the offsets are plain top-left
    numbers and the anchor moves the head as one piece.
    """
    name = attrs.get("name", "")
    if not name:
        raise LayoutGenError("section needs a name prefix", ctx.file, path)
    width, height, hx, vx = _size_leaf(attrs, ctx, box, path, x, y, forced, anchor, 30, exact_only=True)
    if not (hx and vx):
        raise LayoutGenError("section needs an exact size", ctx.file, path)
    head = W("FrameWidgetClass", ctx.claim(name, path), comment=str(attrs.get("note", "")))
    head.set("visible", "0" if attrs.get("hidden") else "1")
    place(head, x, y, width, height, anchor=anchor)
    head.set("priority", fmt(priority))
    accent, _ = ctx.tokens.color_of("$accent", ctx.file, path)
    rule, _ = ctx.tokens.color_of("$rule", ctx.file, path)
    bar = W("PanelWidgetClass", ctx.claim(name + "Bar", path))
    bar.set("visible", "1").set("ignorepointer", "1")
    place(bar, 0, 4, 3, 16)
    bar.set("color", color_prop(accent)).set("priority", "0").set("style", PANEL_STYLE)
    lbl = W("TextWidgetClass", ctx.claim(name + "Lbl", path))
    lbl.set("visible", "1").set("ignorepointer", "1")
    place(lbl, 12, 0, width - 12, 24)
    _color(lbl, attrs, ctx, path, "$accent")
    lbl.set("priority", "1")
    _text_font(lbl, attrs, ctx, path, "header")
    lbl.set(key("text halign"), "left").set(key("text valign"), "center")
    line = W("PanelWidgetClass", ctx.claim(name + "Rule", path))
    line.set("visible", "1").set("ignorepointer", "1")
    place(line, 0, height - 1, width, 1)
    line.set("color", color_prop(rule)).set("priority", "2").set("style", PANEL_STYLE)
    head.children = [bar, lbl, line]
    return [head]


BUILDERS.update({
    "vbox": _b_vbox, "hbox": _b_hbox, "text": _b_text, "button": _b_button,
    "field": _b_field, "section": _b_section,
})


ROW_ATTRS = {"name", "note", "h", "click", "stack", "color", "children"}
#: Property values the engine wants bare (identifiers), not quoted.
BARE_KEYS = frozenset({"style", "mode", "stretch mode", "text halign", "text valign",
                       "fixaspect", "halign", "valign", "content_halign", "content_valign"})


def _props(w: W, props, ctx: Ctx, path: str) -> W:
    """Literal `key value` pairs for what the primitives do not model."""
    if props is None:
        return w
    if not isinstance(props, dict):
        raise LayoutGenError("props must be an object of key: value", ctx.file, path)
    for k, v in props.items():
        if isinstance(v, bool):
            w.set(key(k), "1" if v else "0")
        elif _is_number(v):
            w.set(key(k), fmt(v))
        elif isinstance(v, str):
            if '"' in v:
                raise LayoutGenError(f"a quote inside {k!r} hangs the engine's layout parser", ctx.file, path)
            w.set(key(k), v if k in BARE_KEYS else quoted(v))
        else:
            raise LayoutGenError(f"{k}: a prop is a number, a string or a bool", ctx.file, path)
    return w


def _engine_children(attrs: dict, ctx: Ctx, inner: Box, path: str, forced_h) -> list[W]:
    """Children of an engine container: each at 0 0, one widget apiece."""
    out: list[W] = []
    for i, child in enumerate(attrs.get("children", [])):
        _kind, kattrs = _unpack(child, ctx.file, f"{path}.{i}")
        if kattrs.get("size") == "fill" or kattrs.get("h") == "fill" or kattrs.get("w") == "fill":
            raise LayoutGenError("a stack child cannot fill: the container's size is its children's",
                                 ctx.file, f"{path}.{i}")
        own_h = "h" in kattrs or "size" in kattrs
        made = emit(child, ctx, inner, f"{path}.{i}", i, placed=(0.0, 0.0, None, None if own_h else forced_h))
        if len(made) != 1:
            raise LayoutGenError("an engine container's child must be one widget", ctx.file, f"{path}.{i}")
        out += made
    return out


def _b_stack(attrs, ctx, box, path, x, y, forced, anchor, priority) -> list[W]:
    w = _common_leaf("WrapSpacerWidgetClass", attrs, ctx, path, ignore=False)
    width, _h, hx, _vx = _size_leaf(attrs, ctx, box, path, x, y, (forced[0], 0.0), anchor, 0)
    place(w, x, y, width, 0, hx, True, anchor)
    w.set("priority", fmt(priority)).set("Padding", "0").set("Margin", "0").set(key("Size To Content V"), "1")
    inner = Box(width if hx else box.w, None, prop_w=not hx, engine=True)
    w.children = _engine_children(attrs, ctx, inner, path, None)
    return [w]


def _b_hrow(attrs, ctx, box, path, x, y, forced, anchor, priority) -> list[W]:
    """A GridSpacer of one row that sizes itself: children keep their pixel
    widths, labels may be `auto`, gaps are empty panels."""
    name = attrs.get("name")
    w = W("GridSpacerWidgetClass", ctx.claim(name, path) if name else ctx.hrow_name(path),
          comment=str(attrs.get("note", "")))
    w.set("visible", "0" if attrs.get("hidden") else "1")
    height = forced[1] if forced[1] is not None else attrs.get("h")
    if height is None:
        raise LayoutGenError("hrow needs h", ctx.file, path)
    height = ctx.tokens.number(height, ctx.file, path, "h")
    place(w, x, y, 0, 0, anchor=anchor)
    kids = list(attrs.get("children", []))
    w.set("priority", fmt(priority)).set("Padding", "0").set("Margin", "0")
    w.set(key("Size To Content H"), "1").set(key("Size To Content V"), "1")
    w.set("Columns", fmt(max(1, len(kids)))).set("Rows", "1")
    inner = Box(None, height, engine=True)
    w.children = _engine_children(attrs, ctx, inner, path, height)
    return [w]


def _b_grid(attrs, ctx, box, path, x, y, forced, anchor, priority) -> list[W]:
    w = _common_leaf("GridSpacerWidgetClass", attrs, ctx, path, ignore=False)
    width, height, hx, vx = _size_leaf(attrs, ctx, box, path, x, y, forced, anchor, None, exact_only=True)
    if not (hx and vx):
        raise LayoutGenError("grid needs an exact size", ctx.file, path)
    cols = int(ctx.tokens.number(attrs.get("cols", 1), ctx.file, path, "cols"))
    rows = int(ctx.tokens.number(attrs.get("rows", 1), ctx.file, path, "rows"))
    gap = ctx.tokens.number(attrs.get("gap", 0), ctx.file, path, "gap")
    if cols < 1 or rows < 1:
        raise LayoutGenError("cols and rows must be at least 1", ctx.file, path)
    # A GridSpacer draws every extra child stacked in the last cell rather
    # than complaining, so nothing downstream would report it.
    n = len(attrs.get("children", []))
    if n > cols * rows:
        raise LayoutGenError(f"grid holds {cols * rows} cells, {n} children given", ctx.file, path)
    place(w, x, y, width, height, anchor=anchor)
    w.set("priority", fmt(priority)).set("Padding", fmt(gap)).set("Margin", "0")
    w.set("Columns", fmt(cols)).set("Rows", fmt(rows))
    cell_w = (width - gap * (cols - 1)) / cols
    cell_h = (height - gap * (rows - 1)) / rows
    inner = Box(cell_w, cell_h, engine=True)
    out: list[W] = []
    for i, child in enumerate(attrs.get("children", [])):
        made = emit(child, ctx, inner, f"{path}.{i}", i, placed=(0.0, 0.0, cell_w, cell_h))
        if len(made) != 1:
            raise LayoutGenError("a grid cell must be one widget", ctx.file, f"{path}.{i}")
        out += made
    w.children = out
    return [w]


def _b_keypad(attrs, ctx, box, path, x, y, forced, anchor, priority) -> list[W]:
    keys = attrs.get("keys")
    if not isinstance(keys, list) or not keys:
        raise LayoutGenError("keypad needs keys: [{name, glyph}, ...]", ctx.file, path)
    children = []
    for i, k in enumerate(keys):
        if not (isinstance(k, dict) and isinstance(k.get("name"), str) and isinstance(k.get("glyph"), str)):
            raise LayoutGenError(f"keys[{i}] must be {{name, glyph}}", ctx.file, path)
        children.append({"button": {"name": k["name"], "text": k["glyph"], "glyph": True,
                                    "font": attrs.get("font", "header")}})
    grid_attrs = {k: v for k, v in attrs.items() if k in ALLOWED["grid"]}
    grid_attrs["children"] = children
    return _b_grid(grid_attrs, ctx, box, path, x, y, forced, anchor, priority)


def _build_row(fname: str, rdesc, ctx: Ctx, row_w: float) -> None:
    """One row template of a list, written as its own file `<fname>.layout`."""
    if not isinstance(fname, str) or not fname:
        raise LayoutGenError("a row file needs a name", ctx.file, "rows")
    node = f"rows.{fname}"
    if not (isinstance(rdesc, dict) and list(rdesc) == ["row"] and isinstance(rdesc["row"], dict)):
        raise LayoutGenError('a row template is {"row": {...}}', ctx.file, node)
    attrs = rdesc["row"]
    extra = sorted(set(attrs) - ROW_ATTRS)
    if extra:
        raise LayoutGenError(f"row does not take {extra}", ctx.file, node)
    rctx = ctx.fresh()
    name = rctx.claim(attrs.get("name", ""), node)
    # Only a plain row's root is a PanelWidgetClass; a click row is a button
    # and a stack row a spacer, and neither paints a background.
    if "color" in attrs and (attrs.get("click") or attrs.get("stack")):
        ctx.note(node, "row color is only painted on a plain (non-click, non-stack) row")
    if attrs.get("stack"):
        root = W("WrapSpacerWidgetClass", name)
        root.set("visible", "1")
        place(root, 0, 0, 1, 0, hexact=False)
        root.set("Padding", "0").set("Margin", "0").set(key("Size To Content V"), "1")
        inner = Box(row_w, None, prop_w=True, engine=True)
        rctx.chain.append(0)
        root.children = _engine_children(attrs, rctx, inner, node, None)
    else:
        height = attrs.get("h")
        if height is None:
            raise LayoutGenError("a row needs h (or stack: true)", ctx.file, node)
        height = rctx.tokens.number(height, ctx.file, node, "h")
        if attrs.get("click"):
            root = W("ButtonWidgetClass", name)
        elif "color" in attrs:
            root = W("PanelWidgetClass", name)
        else:
            root = W("FrameWidgetClass", name)
        root.set("visible", "1")
        place(root, 0, 0, 1, height, hexact=False)
        if attrs.get("click"):
            root.set("text", quoted(""))
        if root.cls == "PanelWidgetClass":
            _color(root, attrs, rctx, node, "$panel")
            root.set("style", PANEL_STYLE)
        inner = Box(row_w, height, prop_w=True)
        rctx.chain.append(0)
        for i, child in enumerate(attrs.get("children", [])):
            root.children += emit(child, rctx, inner, f"{node}.{i}", i)
    root.comment = str(attrs.get("note", ""))
    head = [GENERATED_MARK + ctx.file + f" ({node}) -- edit the source, not this file."]
    text = "\n".join(head) + "\n" + render(root) + "\n"
    target = f"{ctx.layout_dir}/{fname}.layout" if ctx.layout_dir else f"{fname}.layout"
    if target in ctx.files:
        raise LayoutGenError(f"row file {fname!r} is emitted twice", ctx.file, node)
    ctx.files[target] = text


def _b_list(attrs, ctx, box, path, x, y, forced, anchor, priority) -> list[W]:
    scroll = _common_leaf("ScrollWidgetClass", attrs, ctx, path, ignore=False)
    width, height, hx, vx = _size_leaf(attrs, ctx, box, path, x, y, forced, anchor, None, exact_only=True)
    if not (hx and vx):
        raise LayoutGenError("list needs an exact size", ctx.file, path)
    place(scroll, x, y, width, height, anchor=anchor)
    scroll.set("priority", fmt(priority)).set("clipchildren", "1").set(key("Scrollbar V"), "1")
    stack_name = attrs.get("stack")
    if not isinstance(stack_name, str) or not stack_name:
        raise LayoutGenError("list needs stack: the name of its spacer (scripts add rows into it)", ctx.file, path)
    spacer = W("WrapSpacerWidgetClass", ctx.claim(stack_name, path))
    spacer.set("visible", "1")
    place(spacer, 0, 0, 1, 0, hexact=False)
    spacer.set("priority", "0").set("Padding", "0").set("Margin", "0").set(key("Size To Content V"), "1")
    scroll.children = [spacer]
    if attrs.get("children"):
        spacer.children = _engine_children(attrs, ctx, Box(width - SCROLLBAR_UNITS, None, prop_w=True, engine=True), path, None)
    rows = attrs.get("rows", {})
    if not isinstance(rows, dict):
        raise LayoutGenError("rows must be an object of {file: {row: ...}}", ctx.file, path)
    for fname, rdesc in rows.items():
        _build_row(fname, rdesc, ctx, width - SCROLLBAR_UNITS)
    return [scroll]


def _b_raw_like(cls: str, attrs, ctx, box, path, x, y, forced, anchor, priority) -> list[W]:
    w = _common_leaf(cls, attrs, ctx, path, ignore=False)
    width, height, hx, vx = _size_leaf(attrs, ctx, box, path, x, y, forced, anchor, None)
    place(w, x, y, width, height, hx, vx, anchor)
    if "color" in attrs:
        _color(w, attrs, ctx, path, "$text")
    w.set("priority", fmt(priority))
    if "font" in attrs:
        font, from_token = ctx.tokens.font_of(attrs["font"], ctx.file, path)
        if not from_token:
            ctx.note(path, "font given as a literal -- use a $font token")
        w.set("font", quoted(font["face"])).set(key("exact text"), "1")
        if not font["fixed"]:
            w.set(key("exact text size"), fmt(font["size"]))
    _props(w, attrs.get("props"), ctx, path)
    inner = Box(width if hx else box.w, height if vx else box.h, prop_w=not hx)
    w.children = _children(attrs, ctx, inner, path)
    return [w]


def _b_listbox(attrs, ctx, box, path, x, y, forced, anchor, priority) -> list[W]:
    return _b_raw_like("TextListboxWidgetClass", attrs, ctx, box, path, x, y, forced, anchor, priority)


def _b_map(attrs, ctx, box, path, x, y, forced, anchor, priority) -> list[W]:
    """The engine's own map: position/size and `clipchildren 1`, nothing
    else -- no `priority`, because none changes its paint order (native
    rendering after the scripted UI, always on top, measured gui-layouts.md
    §19); no `children`, because that same measurement is what the map
    paints over, whichever side of it they are declared on."""
    if attrs.get("children"):
        raise LayoutGenError("map paints over its children -- put overlays beside it", ctx.file, path)
    w = _common_leaf("MapWidgetClass", attrs, ctx, path, ignore=False)
    width, height, hx, vx = _size_leaf(attrs, ctx, box, path, x, y, forced, anchor, None)
    place(w, x, y, width, height, hx, vx, anchor)
    w.set("clipchildren", "1")
    return [w]


def _b_preview(attrs, ctx, box, path, x, y, forced, anchor, priority) -> list[W]:
    worst = max(ctx.chain) if ctx.chain else 0
    if worst > PREVIEW_PRIORITY_MAX:
        raise LayoutGenError(f"priority {worst} above {PREVIEW_PRIORITY_MAX} on the way to the preview -- "
                             "the engine silently draws no model", ctx.file, path)
    return _b_raw_like("ItemPreviewWidgetClass", attrs, ctx, box, path, x, y, forced, anchor, priority)


def _b_raw(attrs, ctx, box, path, x, y, forced, anchor, priority) -> list[W]:
    cls = attrs.get("class")
    if not isinstance(cls, str) or not cls.endswith("Class"):
        raise LayoutGenError("raw needs class: a *WidgetClass name", ctx.file, path)
    ctx.note(path, f"raw {cls}: the generator does not vouch for it")
    return _b_raw_like(cls, attrs, ctx, box, path, x, y, forced, anchor, priority)


BUILDERS.update({
    "stack": _b_stack, "hrow": _b_hrow, "grid": _b_grid, "list": _b_list, "keypad": _b_keypad,
    "listbox": _b_listbox, "map": _b_map, "preview": _b_preview, "raw": _b_raw,
})


def _iconset(attrs: dict, ctx: Ctx, path: str) -> str:
    iconset = attrs.get("set") or ctx.tokens.device.get("iconset")
    if not isinstance(iconset, str) or not iconset:
        raise LayoutGenError("icon needs set, or device.iconset in the tokens", ctx.file, path)
    return iconset


def _b_icon(attrs, ctx, box, path, x, y, forced, anchor, priority) -> list[W]:
    """A sprite of an imageset, alpha-blended and tinted by `color`.

    No `"stretch mode"`, unlike `_b_image`'s three ImageWidget traps: an
    imageset sprite already scales itself from the rect its own entry
    declares, and most vanilla imageset-ref ImageWidgets set no stretch mode
    at all (measured 2026-09-04, skill gui-layouts.md: 989 of 1392) -- this
    is the measured default, not an oversight shared with `_b_image`.
    """
    image = attrs.get("image")
    if not isinstance(image, str) or not image:
        raise LayoutGenError("icon needs image: the sprite's name in the set", ctx.file, path)
    iconset = _iconset(attrs, ctx, path)
    w = _common_leaf("ImageWidgetClass", attrs, ctx, path)
    width, height, _hx, _vx = _size_leaf(attrs, ctx, box, path, x, y, forced, anchor, None, exact_only=True)
    place(w, x, y, width, height, anchor=anchor)
    _color(w, attrs, ctx, path, "$text")
    w.set("priority", fmt(priority))
    w.set("image0", quoted(f"set:{iconset} image:{image}"))
    w.set("mode", "blend").set(key("src alpha"), "1")
    return [w]


def _b_image(attrs, ctx, box, path, x, y, forced, anchor, priority) -> list[W]:
    """A texture file: `mode blend` + `"src alpha" 1` so alpha counts, and
    `"stretch mode" stretch_w_h` so the picture is scaled, not cropped --
    the three ImageWidget traps of gui-layouts.md §12, written once."""
    file = attrs.get("file")
    if not isinstance(file, str) or not file.endswith(".paa"):
        raise LayoutGenError("image needs file: a .paa path relative to the pbo prefix", ctx.file, path)
    w = _common_leaf("ImageWidgetClass", attrs, ctx, path)
    width, height, hx, vx = _size_leaf(attrs, ctx, box, path, x, y, forced, anchor, None)
    place(w, x, y, width, height, hx, vx, anchor)
    _color(w, attrs, ctx, path, "$white")
    w.set("priority", fmt(priority))
    w.set("image0", quoted(file)).set("mode", "blend").set(key("src alpha"), "1")
    if attrs.get("stretch", True):
        w.set(key("stretch mode"), "stretch_w_h")
    _props(w, attrs.get("props"), ctx, path)
    return [w]


def _b_badge(attrs, ctx, box, path, x, y, forced, anchor, priority) -> list[W]:
    """A count on a coloured disc (the set's `badge` sprite): <Name> holds
    <Name>Text. Hidden until a script shows it with a number."""
    iconset = _iconset(attrs, ctx, path)
    name = ctx.claim(attrs.get("name", ""), path)
    disc = W("ImageWidgetClass", name, comment=str(attrs.get("note", "")))
    disc.set("visible", "0" if attrs.get("hidden", True) else "1").set("ignorepointer", "1")
    sized = dict(attrs)
    if "size" not in sized and "w" not in sized and "h" not in sized:
        sized["size"] = [18, 18]
    width, height, _hx, _vx = _size_leaf(sized, ctx, box, path, x, y, forced, anchor, None, exact_only=True)
    place(disc, x, y, width, height, anchor=anchor)
    _color(disc, attrs, ctx, path, "$alert")
    disc.set("priority", fmt(priority))
    disc.set("image0", quoted(f"set:{iconset} image:badge")).set("mode", "blend").set(key("src alpha"), "1")
    label = W("TextWidgetClass", ctx.claim(name + "Text", path))
    label.set("visible", "1").set("ignorepointer", "1")
    place(label, 0, 0, width, height)
    rgba, _ = ctx.tokens.color_of("$screen", ctx.file, path)
    label.set("color", color_prop(rgba)).set("priority", "0")
    _text_font(label, {"font": attrs.get("font", "tiny")}, ctx, path, "tiny")
    label.set(key("text halign"), "center").set(key("text valign"), "center")
    disc.children = [label]
    return [disc]


def _b_header(attrs, ctx, box, path, x, y, forced, anchor, priority) -> list[W]:
    """A page head: the page's icon, its title, its actions -- one row for
    every page, so switching tabs moves nothing."""
    title = attrs.get("title")
    if not isinstance(title, dict) or not title.get("name"):
        raise LayoutGenError('header needs title: {"name": ..., ...label attributes}', ctx.file, path)
    children = []
    if attrs.get("icon"):
        children.append({"icon": {"name": str(title["name"]) + "Icon", "image": attrs["icon"],
                                  "size": [22, 22], "color": "$accent"}})
    label = dict(title)
    label.setdefault("font", attrs.get("font", "title"))
    label.setdefault("color", "$accent")
    label["w"] = "fill"
    children.append({"label": label})
    actions = attrs.get("actions", [])
    if not isinstance(actions, list):
        raise LayoutGenError("header actions must be a list of nodes", ctx.file, path)
    children += actions
    row = {k: v for k, v in attrs.items() if k in ("name", "note", "hidden", "priority", "w", "h", "size", "anchor", "at")}
    if "h" not in row and "size" not in row:
        row["h"] = "$size.header"
    row["gap"] = attrs.get("gap", "$space.gap")
    row["children"] = children
    return _stackbox(row, ctx, box, path, x, y, forced, anchor, priority, vertical=False)


BUILDERS.update({"icon": _b_icon, "image": _b_image, "badge": _b_badge, "header": _b_header})


def build_layout(desc, tokens: Tokens, file: str = "", layout_dir: str = "") -> Emitted:
    """One page description -> its .layout text plus the row files it owns.

    `file` is the description's project-relative path (named in errors and
    in the GENERATED header); `layout_dir` is where the files go
    (`MyMod/gui/layouts`), so the keys of `files` are project-relative.
    """
    if not isinstance(desc, dict):
        raise LayoutGenError("a description is a JSON object", file)
    name = desc.get("layout")
    if not isinstance(name, str) or not name:
        raise LayoutGenError('"layout" (the file name without .layout) is required', file)
    extra = sorted(set(desc) - {"layout", "note", "root", "body"})
    if extra:
        raise LayoutGenError(f"a description does not take {extra}", file)
    if "root" not in desc:
        raise LayoutGenError('"root" is required', file)
    ctx = Ctx(tokens=tokens, file=file, layout_dir=layout_dir)
    kind, attrs = _unpack(desc["root"], file, "root")
    if kind not in ROOT_KINDS:
        raise LayoutGenError(f"root must be a frame, a panel or a button, not {kind}", file, "root")
    if "size" not in attrs or attrs["size"] == "fill":
        raise LayoutGenError("root needs an exact size [w, h]", file, "root")
    root_cls = {"frame": "FrameWidgetClass", "panel": "PanelWidgetClass", "button": "ButtonWidgetClass"}[kind]
    root = W(root_cls, ctx.claim(attrs.get("name", name), "root"), comment=str(attrs.get("note", "")))
    root.set("visible", "0" if attrs.get("hidden") else "1")
    # The root places itself the same way any other node does: a window
    # centred in its host is `anchor: "center"`, not a proportional position
    # that has to be recomputed for every screen (spec 2026-09-04 §3.6).
    anchor = attrs.get("anchor", "")
    if anchor and anchor not in ANCHORS:
        raise LayoutGenError(f"unknown anchor {anchor!r}; one of {sorted(ANCHORS)}", file, "root")
    if attrs.get("size") == "screen":
        if kind != "frame":
            raise LayoutGenError("only a frame root can be the whole screen", file, "root")
        if "inset" in attrs or "at" in attrs or anchor:
            ctx.note("root", "inset/at/anchor are ignored on a screen root")
        place(root, 0, 0, 1, 1, hexact=False, vexact=False)
        inner = Box(None, None)
    else:
        width, height = tokens.pair(attrs["size"], file, "root")
        ax, ay = tokens.pair(attrs.get("at", [0, 0]), file, "root", "at")
        place(root, ax, ay, width, height, anchor=anchor)
        inset = tokens.number(attrs.get("inset", 0), file, "root", "inset")
        inner = Box(width - 2 * inset, height - 2 * inset, ox=inset, oy=inset)
    if kind == "button":
        root.set("text", quoted(""))
        # Root-only: a button root holds page content the way a frame/panel
        # root does, so build_layout (not _b_button) owns it, and none of
        # the nested button's own idiom (text/font/bg/edge/glyph -> Edge/Bg/
        # Text children) applies here. The mirror image of the note
        # `_b_button` already gives a NESTED button for an ignored `children`.
        ignored = [k for k in ("text", "font", "bg", "edge", "glyph") if k in attrs]
        if ignored:
            ctx.note("root", "button root ignores text/font/bg/edge/glyph -- give it children")
    if kind == "panel":
        _color(root, attrs, ctx, "root", "$screen")
        root.set("style", PANEL_STYLE)
    if "priority" in attrs:
        root.set("priority", fmt(_priority(attrs, ctx, "root", 0)))
    children = list(attrs.get("children", []))
    if "body" in desc:
        children.append(desc["body"])
    ctx.chain.append(_priority(attrs, ctx, "root", 0))
    # `on_page` is False for a button root's own children: a button root is
    # a fixed-size compound control (an icon, a label, a badge at specific
    # offsets), never a page an author would otherwise build with vbox/hbox
    # -- unlike a frame/panel root, which the note's advice always fits,
    # whatever size it declares. Narrower than "any root with an exact
    # size" would be: a frame/panel root sized like a small fixed dialog is
    # still exactly the case the note exists to steer, and nothing in this
    # project's own descriptions asks for that to go quiet too.
    for i, child in enumerate(children):
        root.children += emit(child, ctx, inner, f"root.{i}", i, on_page=(kind != "button"))
    head = [GENERATED_MARK + file + " -- edit the source, not this file."]
    head += [f"// {line}" for line in str(desc.get("note", "")).splitlines()]
    text = "\n".join(head) + "\n" + render(root) + "\n"
    target = f"{layout_dir}/{name}.layout" if layout_dir else f"{name}.layout"
    files = {target: text}
    files.update(ctx.files)
    return Emitted(files, ctx.notes)


def target_path(root, sources: dict[str, str], target: str) -> Path:
    """Where a generated key (`<Mod>/gui/layouts/x.layout`) lands on disk.

    The keys of `BuildReport.files` are LOGICAL -- they always start with the
    mod's declared NAME -- while the disk path follows `[build] sources`,
    which may put the mod anywhere under the project (`"."` for a mod whose
    config.cpp sits at the repository root). The two agree only when
    `sources[mod] == mod`, so every caller that needs one from the other goes
    through this one formula.
    """
    head, _, rest = target.partition("/")
    return resolve_mod_dir(root, sources, head) / rest


@dataclass
class BuildReport:
    """`written` = files that differed from what is on disk (and were written
    when `write` was on); `files` = every generated path -> text; `sources`
    = generated path -> the description it came from."""

    written: list[str] = field(default_factory=list)
    unchanged: list[str] = field(default_factory=list)
    notes: list[str] = field(default_factory=list)
    files: dict[str, str] = field(default_factory=dict)
    sources: dict[str, str] = field(default_factory=dict)


def build_project(root, mods: list[str], sources: dict[str, str], mod: str = "",
                  write: bool = True, tokens_path: str | Path | None = None) -> BuildReport:
    """Generate every description under `<root>/ui/<Mod>/` for `mods`.

    Generation completes for every file before anything is written, so a bad
    description leaves the disk exactly as it was. Files are written with LF
    endings, compared after normalising CRLF, so a checkout on either setting
    reads as unchanged.

    `tokens_path` names `ui/tokens.json` (the default, `None`) or wherever
    `[build] tokens` points instead -- absolute, or relative to `root`.
    """
    root = Path(root)
    report = BuildReport()
    wanted = [m for m in mods if not mod or m == mod]
    dirs = [(m, root / UI_DIR / m) for m in wanted if (root / UI_DIR / m).is_dir()]
    if not dirs:
        return report
    tokens_file = Path(tokens_path) if tokens_path is not None else root / UI_DIR / TOKENS_FILE
    if not tokens_file.is_absolute():
        tokens_file = root / tokens_file
    try:
        tokens_label = tokens_file.relative_to(root).as_posix()
    except ValueError:
        tokens_label = str(tokens_file)
    # `Tokens.load`'s own message only names the path -- this caller is the
    # one that knows a ui/<Mod>/ already exists (checked above, via `dirs`),
    # so it is the one that says a tokens file is missing DESPITE that.
    if not tokens_file.is_file():
        raise LayoutGenError(f"{tokens_label} is missing but {UI_DIR}/<Mod>/ exists", tokens_label)
    tokens = Tokens.load(tokens_file, tokens_label)
    for m, ui_dir in dirs:
        for path in sorted(ui_dir.glob("*.json")):
            rel = path.relative_to(root).as_posix()
            try:
                desc = json.loads(path.read_text(encoding="utf-8"))
            except json.JSONDecodeError as exc:
                raise LayoutGenError(f"does not parse: {exc}", rel) from None
            emitted = build_layout(desc, tokens, rel, f"{m}/{LAYOUT_DIR}")
            report.notes += emitted.notes
            for target, text in emitted.files.items():
                if target in report.files:
                    raise LayoutGenError(f"{target} is generated by two descriptions "
                                         f"({report.sources[target]} and {rel})", rel)
                report.files[target] = text
                report.sources[target] = rel
    for target, text in report.files.items():
        out = target_path(root, sources, target)
        current = out.read_text(encoding="utf-8") if out.is_file() else None
        if current is not None and current.replace("\r\n", "\n") == text:
            report.unchanged.append(target)
            continue
        report.written.append(target)
        if write:
            out.parent.mkdir(parents=True, exist_ok=True)
            with out.open("w", encoding="utf-8", newline="\n") as fh:
                fh.write(text)
    return report


def main(argv=None) -> int:
    """`python -m dayz_mcp.layoutgen <project root> [mod]` -- the tool without the server."""
    from .profile import load_profile
    args = list(sys.argv[1:] if argv is None else argv)
    if not args:
        print("usage: python -m dayz_mcp.layoutgen <project root> [mod]")
        return 2
    loaded = load_profile(args[0])
    if not loaded.ok:
        print(loaded.error)
        return 1
    prof = loaded.data
    mod = args[1] if len(args) > 1 else ""
    if mod and mod not in prof.build.mods:
        print(f"{mod!r} is not a mod of this project; it declares: {', '.join(prof.build.mods)}")
        return 1
    try:
        report = build_project(prof.root, prof.build.mods, prof.build.sources, mod, tokens_path=prof.build.tokens)
    except LayoutGenError as exc:
        print(f"refused: {exc}")
        return 1
    for p in report.written:
        print("wrote", p)
    for p in report.unchanged:
        print("unchanged", p)
    for n in report.notes:
        print("note", n)
    return 0


if __name__ == "__main__":
    sys.exit(main())
