"""JSON page descriptions -> .layout text, one engine idiom per primitive.

Spec: E:/openzone/docs/specs/2026-09-04-ui-layout-generator-design.md, §3.
The engine lays out lists, stacks, rows of self-sized labels and wrapped
text by itself (measured 2026-09-04, skill gui-layouts.md §24). What it
cannot do -- a `fill` in a column, a flexible column in a row, the width of
a row under a scrollbar -- is computed here ONCE, from the exact size of
the nearest exact ancestor. Nothing proportional is ever written with a
magnitude above 1, and every primitive writes the same idiom every time.
"""
from __future__ import annotations

import json
import sys
from dataclasses import dataclass, field
from pathlib import Path

#: A proportional-width child of a ScrollWidget with "Scrollbar V" 1 gets
#: the scroll's width minus this many layout units (measured 2026-09-04).
SCROLLBAR_UNITS = 10
#: First line of every generated file; mod_lint's layout-stale rule keys on it.
GENERATED_MARK = "// GENERATED by dayz-mcp layout_build from "
#: An ItemPreviewWidget under a priority above this draws nothing (measured).
PREVIEW_PRIORITY_MAX = 256
FONT_FACE_DEFAULT = "gui/fonts/sdf_MetronBook24"
PANEL_STYLE = "rover_sim_colorable"
#: Where a mod keeps its layouts, under the mod's source folder.
LAYOUT_DIR = "gui/layouts"
#: Where a project keeps descriptions: <root>/ui/tokens.json, <root>/ui/<Mod>/*.json.
UI_DIR = "ui"
TOKENS_FILE = "tokens.json"


class LayoutGenError(ValueError):
    """A description the generator refuses: the file, the node and why."""

    def __init__(self, message: str, file: str = "", node: str = ""):
        super().__init__(message)
        self.message = message
        self.file = file
        self.node = node

    def __str__(self) -> str:
        where = " ".join(p for p in (self.file, self.node) if p)
        return f"{where}: {self.message}" if where else self.message


def fmt(value: float) -> str:
    """A number the way vanilla layouts write it: integers bare, floats to 3 places."""
    if isinstance(value, bool):
        raise TypeError("a bool is not a layout number")
    value = float(value)
    if value.is_integer():
        return str(int(value))
    return f"{value:.3f}".rstrip("0").rstrip(".")


def _is_number(value) -> bool:
    return isinstance(value, (int, float)) and not isinstance(value, bool)


@dataclass
class Tokens:
    """`ui/tokens.json`: the numbers, colours and fonts written once."""

    color: dict[str, list[float]] = field(default_factory=dict)
    font: dict[str, dict] = field(default_factory=dict)
    space: dict[str, float] = field(default_factory=dict)
    size: dict[str, float] = field(default_factory=dict)
    device: dict = field(default_factory=dict)
    file: str = "ui/tokens.json"

    @classmethod
    def from_text(cls, text: str, file: str = "ui/tokens.json") -> "Tokens":
        try:
            data = json.loads(text)
        except json.JSONDecodeError as exc:
            raise LayoutGenError(f"tokens do not parse: {exc}", file) from None
        if not isinstance(data, dict):
            raise LayoutGenError("tokens must be a JSON object", file)
        t = cls(file=file)
        for name, rgba in dict(data.get("color") or {}).items():
            good = (isinstance(rgba, list) and len(rgba) == 4
                    and all(_is_number(v) and 0 <= v <= 1 for v in rgba))
            if not good:
                raise LayoutGenError(f"color.{name} must be four numbers 0..1", file)
            t.color[name] = [float(v) for v in rgba]
        for name, spec in dict(data.get("font") or {}).items():
            good = (isinstance(spec, dict) and _is_number(spec.get("size"))
                    and isinstance(spec.get("face", FONT_FACE_DEFAULT), str)
                    and isinstance(spec.get("fixed", False), bool))
            if not good:
                raise LayoutGenError(f'font.{name} must be {{"face": str, "size": number, "fixed": bool}}', file)
            t.font[name] = {"face": spec.get("face", FONT_FACE_DEFAULT),
                            "size": float(spec["size"]), "fixed": bool(spec.get("fixed", False))}
        for group in ("space", "size"):
            for name, value in dict(data.get(group) or {}).items():
                if not _is_number(value):
                    raise LayoutGenError(f"{group}.{name} must be a number", file)
                getattr(t, group)[name] = float(value)
        t.device = dict(data.get("device") or {})
        return t

    def number(self, value, file: str, node: str, what: str = "size") -> float:
        """A number, or a `$space.<name>` / `$size.<name>` reference."""
        if isinstance(value, bool):
            raise LayoutGenError(f"{what} must be a number, not a bool", file, node)
        if _is_number(value):
            return float(value)
        if isinstance(value, str) and value.startswith("$"):
            group, _, name = value[1:].partition(".")
            table = {"space": self.space, "size": self.size}.get(group)
            if table is None or name not in table:
                raise LayoutGenError(f"unknown token {value!r} for {what}", file, node)
            return table[name]
        raise LayoutGenError(f"{what} must be a number or a $space/$size token, got {value!r}", file, node)

    def pair(self, value, file: str, node: str, what: str = "size") -> tuple[float, float]:
        """`[w, h]` of numbers or tokens, or `$device.<name>` naming a two-number token."""
        if isinstance(value, str) and value.startswith("$device."):
            got = self.device.get(value[len("$device."):])
            if not (isinstance(got, list) and len(got) == 2 and all(_is_number(v) for v in got)):
                raise LayoutGenError(f"{value!r} is not a [w, h] device token", file, node)
            return float(got[0]), float(got[1])
        if isinstance(value, list) and len(value) == 2:
            return (self.number(value[0], file, node, what + "[0]"),
                    self.number(value[1], file, node, what + "[1]"))
        raise LayoutGenError(f"{what} must be [w, h] or a $device token, got {value!r}", file, node)

    def color_of(self, value, file: str, node: str) -> tuple[list[float], bool]:
        """`(rgba, from_token)`: `$name` looks the colour up; a literal list passes and is reported."""
        if isinstance(value, str) and value.startswith("$"):
            name = value[1:]
            if name.startswith("color."):
                name = name[len("color."):]
            if name not in self.color:
                raise LayoutGenError(f"unknown color token {value!r}", file, node)
            return list(self.color[name]), True
        if isinstance(value, list) and len(value) == 4 and all(_is_number(v) for v in value):
            return [float(v) for v in value], False
        raise LayoutGenError(f"color must be a $token or four numbers, got {value!r}", file, node)

    def font_of(self, value, file: str, node: str) -> tuple[dict, bool]:
        """`(font, from_token)`: a token name (`header`, `$font.header`) or a literal spec."""
        if isinstance(value, str):
            name = value[1:] if value.startswith("$") else value
            if name.startswith("font."):
                name = name[len("font."):]
            if name in self.font:
                return dict(self.font[name]), True
            raise LayoutGenError(f"unknown font token {value!r}", file, node)
        if isinstance(value, dict) and _is_number(value.get("size")):
            return {"face": value.get("face", FONT_FACE_DEFAULT), "size": float(value["size"]),
                    "fixed": bool(value.get("fixed", False))}, False
        raise LayoutGenError(f'font must be a token name or {{"face", "size"}}, got {value!r}', file, node)
