"""JSON descriptions -> .layout text. The bar: every idiom the generator
writes is one the engine was MEASURED to lay out (gui-layouts.md §24), every
number it derives is derived once, and nothing it writes trips lint_layout."""
import json

import pytest

from dayz_mcp import layoutgen
from dayz_mcp.layoutgen import LayoutGenError, Tokens, fmt

TOKENS = {
    "color": {"screen": [0.055, 0.075, 0.095, 1], "panel": [0.10, 0.135, 0.17, 1],
              "raised": [0.135, 0.18, 0.225, 1], "edge": [0.22, 0.30, 0.38, 1],
              "text": [0.90, 0.93, 0.95, 1], "muted": [0.58, 0.65, 0.71, 1],
              "faint": [0.37, 0.45, 0.52, 1], "accent": [0.31, 0.71, 0.91, 1],
              "alert": [0.94, 0.54, 0.14, 1], "rule": [1, 1, 1, 0.08],
              "pick": [0.31, 0.71, 0.91, 0.18], "none": [0, 0, 0, 0], "white": [1, 1, 1, 1]},
    "font": {"title": {"size": 18}, "header": {"size": 16}, "body": {"size": 15},
             "hint": {"size": 14}, "small": {"size": 13},
             "field": {"face": "gui/fonts/MetronBook14", "size": 14, "fixed": True}},
    "space": {"page": 20, "gap": 10, "tight": 6},
    "size": {"button": 30, "field": 28, "header": 34, "hint": 22, "contactRow": 55},
    "device": {"page": [1306, 518]},
}


def tokens() -> Tokens:
    return Tokens.from_text(json.dumps(TOKENS), "ui/tokens.json")


def test_fmt_writes_numbers_the_way_vanilla_layouts_do():
    assert fmt(30) == "30" and fmt(30.0) == "30" and fmt(0.918) == "0.918"
    assert fmt(0.5) == "0.5" and fmt(1 / 3) == "0.333"


def test_tokens_resolve_numbers_colors_and_fonts():
    t = tokens()
    assert t.number("$space.page", "f", "n") == 20.0
    assert t.number("$size.button", "f", "n") == 30.0
    assert t.number(12, "f", "n") == 12.0
    rgba, from_token = t.color_of("$accent", "f", "n")
    assert rgba == [0.31, 0.71, 0.91, 1.0] and from_token
    rgba, from_token = t.color_of([1, 0, 0, 1], "f", "n")
    assert rgba == [1.0, 0.0, 0.0, 1.0] and not from_token
    font, from_token = t.font_of("header", "f", "n")
    assert font == {"face": layoutgen.FONT_FACE_DEFAULT, "size": 16.0, "fixed": False} and from_token
    assert t.font_of("field", "f", "n")[0]["fixed"] is True
    assert t.pair("$device.page", "f", "n") == (1306.0, 518.0)
    assert t.pair([640, "$size.contactRow"], "f", "n") == (640.0, 55.0)


@pytest.mark.parametrize("value, what", [
    ("$space.nope", "unknown token"), ("$nope.page", "unknown token"),
    ("fill", "must be a number"), (True, "not a bool"),
])
def test_a_bad_number_names_the_file_the_node_and_the_reason(value, what):
    with pytest.raises(LayoutGenError) as caught:
        tokens().number(value, "ui/x.json", "root.0", "w")
    assert what in str(caught.value) and "ui/x.json root.0" in str(caught.value)


def test_a_bad_color_or_font_token_is_refused():
    with pytest.raises(LayoutGenError, match="unknown color token"):
        tokens().color_of("$mauve", "f", "n")
    with pytest.raises(LayoutGenError, match="unknown font token"):
        tokens().font_of("mono", "f", "n")


def test_tokens_file_is_validated_shape_by_shape():
    with pytest.raises(LayoutGenError, match="color.bad must be four numbers 0..1"):
        Tokens.from_text('{"color": {"bad": [1, 2]}}', "ui/tokens.json")
    with pytest.raises(LayoutGenError, match="font.h must be"):
        Tokens.from_text('{"font": {"h": "big"}}', "ui/tokens.json")
    with pytest.raises(LayoutGenError, match="space.page must be a number"):
        Tokens.from_text('{"space": {"page": "20"}}', "ui/tokens.json")
    with pytest.raises(LayoutGenError, match="do not parse"):
        Tokens.from_text("{", "ui/tokens.json")


from dayz_mcp.layoutgen import build_layout
from dayz_mcp.layoutlint import lint_layout


def page(body, root=None, layout="oz_page", note=""):
    return {"layout": layout, "note": note,
            "root": root or {"frame": {"name": "OZ_Page", "size": [640, 518], "inset": "$space.page"}},
            "body": body}


def build(desc):
    return build_layout(desc, tokens(), "ui/MyMod/oz_page.json", "MyMod/gui/layouts")


def clean(text: str) -> list:
    return [(f.check, f.message) for f in lint_layout(text, "gen.layout")]


def test_a_frame_root_with_one_label_renders_the_vanilla_shape():
    out = build(page({"label": {"name": "Title", "text": "Hello", "font": "header", "color": "$accent",
                                "w": 300, "h": 26}}, note="A page."))
    assert list(out.files) == ["MyMod/gui/layouts/oz_page.layout"]
    text = out.files["MyMod/gui/layouts/oz_page.layout"]
    assert text.splitlines()[0] == "// GENERATED by dayz-mcp layout_build from ui/MyMod/oz_page.json -- edit the source, not this file."
    assert text.splitlines()[1] == "// A page."
    assert text.splitlines()[2] == "FrameWidgetClass OZ_Page {"
    assert (
        "  TextWidgetClass Title {\n"
        "   visible 1\n"
        "   ignorepointer 1\n"
        "   position 20 20\n"
        "   size 300 26\n"
        "   hexactpos 1\n"
        "   vexactpos 1\n"
        "   hexactsize 1\n"
        "   vexactsize 1\n"
        "   color 0.31 0.71 0.91 1\n"
        "   priority 0\n"
        '   text "Hello"\n'
        '   font "gui/fonts/sdf_MetronBook24"\n'
        '   "exact text" 1\n'
        '   "exact text size" 16\n'
        '   "text halign" left\n'
        '   "text valign" center\n'
        "  }\n"
    ) in text
    assert clean(text) == []
    assert out.notes == []


def test_root_props_inset_and_children_offsets():
    out = build(page({"panel": {"name": "Bg", "size": "fill", "color": "$panel"}}))
    text = out.files["MyMod/gui/layouts/oz_page.layout"]
    assert " visible 1\n position 0 0\n size 640 518\n hexactpos 1\n vexactpos 1\n hexactsize 1\n vexactsize 1\n" in text
    # size "fill" at the inner origin is the full inner box, exact
    assert "  PanelWidgetClass Bg {\n   visible 1\n   ignorepointer 1\n   position 20 20\n   size 600 478\n" in text
    assert "   style rover_sim_colorable\n" in text


def test_a_label_can_size_itself_and_anchor_right():
    out = build(page({"label": {"name": "Where", "anchor": "right", "at": [12, 6], "w": "auto", "h": 25,
                                "text": "nearby", "font": "small", "color": "$muted", "align": "right"}}))
    text = out.files["MyMod/gui/layouts/oz_page.layout"]
    assert "   halign right_ref\n   position 32 26\n   size 0 25\n" in text
    assert '   "size to text h" 1\n' in text and '   "text halign" right\n' in text
    assert clean(text) == []


def test_rule_chip_and_hidden_widgets():
    out = build(page({"frame": {"name": "Card", "at": [0, 0], "size": [300, 55], "children": [
        {"chip": {"name": "Chip"}},
        {"rule": {"name": "Line", "anchor": "bottom", "at": [22, 0], "w": "fill"}},
        {"panel": {"name": "Pick", "size": "fill", "color": "$pick", "hidden": True}},
    ]}}))
    text = out.files["MyMod/gui/layouts/oz_page.layout"]
    assert "PanelWidgetClass Chip {\n     visible 0\n     ignorepointer 1\n     position 0 0\n     size 4 1\n     hexactpos 1\n     vexactpos 1\n     hexactsize 1\n     vexactsize 0\n     color 1 1 1 1\n     priority 0\n" in text
    assert "PanelWidgetClass Line {\n     visible 1\n     ignorepointer 1\n     valign bottom_ref\n     position 22 0\n     size 278 1\n" in text
    assert "PanelWidgetClass Pick {\n     visible 0\n" in text and "     priority 2\n" in text
    assert clean(text) == []


def test_at_on_a_page_child_is_noted_but_hidden_overlays_are_not():
    out = build(page({"frame": {"name": "Wrap", "size": [100, 100], "children": [
        {"panel": {"name": "A", "at": [5, 5], "size": [10, 10], "color": "$panel"}},
        {"panel": {"name": "Over", "at": [5, 5], "size": [10, 10], "color": "$panel", "hidden": True}},
    ]}}))
    assert out.notes == []
    out = build(page({"panel": {"name": "Loose", "at": [5, 5], "size": [10, 10], "color": "$panel"}}))
    assert out.notes == ["ui/MyMod/oz_page.json root.0: `at` on a page child -- build the page with vbox/hbox"]


@pytest.mark.parametrize("desc, message", [
    ({"layout": "x", "root": {"frame": {"name": "R", "size": [1, 1]}},
      "body": {"label": {"name": "A", "h": 20}, "panel": {}}}, "exactly one primitive key"),
    ({"layout": "x", "root": {"frame": {"name": "R", "size": [1, 1]}},
      "body": {"sparkle": {"name": "A"}}}, "unknown primitive 'sparkle'"),
    ({"layout": "x", "root": {"frame": {"name": "R", "size": [1, 1]}},
      "body": {"label": {"name": "A", "h": 20, "bold": 1}}}, "label does not take ['bold']"),
    ({"layout": "x", "root": {"frame": {"name": "R", "size": [100, 100]}},
      "body": {"frame": {"name": "F", "size": [50, 50], "children": [
          {"panel": {"name": "Dup", "size": [1, 1], "color": "$panel"}},
          {"panel": {"name": "Dup", "size": [1, 1], "color": "$panel"}}]}}}, "duplicate widget name 'Dup'"),
    ({"layout": "x", "root": {"frame": {"name": "R", "size": [100, 100]}},
      "body": {"label": {"name": "A", "h": 20, "text": 'say "hi"'}}}, "quote inside text"),
    ({"layout": "x", "root": {"label": {"name": "R"}}}, "root must be a frame or a panel"),
    ({"layout": "x", "root": {"frame": {"name": "R"}}}, "root needs an exact size"),
    ({"layout": "x", "root": {"frame": {"name": "R", "size": [100, 100]}},
      "body": {"label": {"name": "A", "h": "auto"}}}, "auto is only a label's width"),
])
def test_refusals_name_the_node(desc, message):
    with pytest.raises(LayoutGenError) as caught:
        build_layout(desc, tokens(), "ui/MyMod/x.json", "MyMod/gui/layouts")
    assert message in str(caught.value) and "ui/MyMod/x.json" in str(caught.value)


def test_literal_colors_and_fonts_are_allowed_but_noted():
    out = build(page({"label": {"name": "A", "h": 20, "color": [1, 0, 0, 1], "font": {"size": 12}}}))
    assert out.notes == [
        "ui/MyMod/oz_page.json root.0: color given as a literal -- use a $color token",
        "ui/MyMod/oz_page.json root.0: font given as a literal -- use a $font token",
    ]
