"""JSON descriptions -> .layout text. The bar: every idiom the generator
writes is one the engine was MEASURED to lay out (gui-layouts.md §24), every
number it derives is derived once, and nothing it writes trips lint_layout."""
import json

import pytest

from dayz_mcp import layoutgen
from dayz_mcp.layoutgen import LayoutGenError, Tokens, fmt

TOKENS = {
    "color": {"screen": [0.055, 0.075, 0.095, 1], "panel": [0.10, 0.135, 0.17, 1],
              "raised": [0.135, 0.18, 0.225, 1], "edge": [0.22, 0.30, 0.38, 1],
              "text": [0.90, 0.93, 0.95, 1], "muted": [0.58, 0.65, 0.71, 1],
              "faint": [0.37, 0.45, 0.52, 1], "accent": [0.31, 0.71, 0.91, 1],
              "alert": [0.94, 0.54, 0.14, 1], "rule": [1, 1, 1, 0.08],
              "pick": [0.31, 0.71, 0.91, 0.18], "none": [0, 0, 0, 0], "white": [1, 1, 1, 1]},
    "font": {"title": {"size": 18}, "header": {"size": 16}, "body": {"size": 15},
             "hint": {"size": 14}, "small": {"size": 13},
             "field": {"face": "gui/fonts/MetronBook14", "size": 14, "fixed": True}},
    "space": {"page": 20, "gap": 10, "tight": 6},
    "size": {"button": 30, "field": 28, "header": 34, "hint": 22, "contactRow": 55},
    "device": {"page": [1306, 518]},
}


def tokens() -> Tokens:
    return Tokens.from_text(json.dumps(TOKENS), "ui/tokens.json")


def test_fmt_writes_numbers_the_way_vanilla_layouts_do():
    assert fmt(30) == "30" and fmt(30.0) == "30" and fmt(0.918) == "0.918"
    assert fmt(0.5) == "0.5" and fmt(1 / 3) == "0.333"


def test_tokens_resolve_numbers_colors_and_fonts():
    t = tokens()
    assert t.number("$space.page", "f", "n") == 20.0
    assert t.number("$size.button", "f", "n") == 30.0
    assert t.number(12, "f", "n") == 12.0
    rgba, from_token = t.color_of("$accent", "f", "n")
    assert rgba == [0.31, 0.71, 0.91, 1.0] and from_token
    rgba, from_token = t.color_of([1, 0, 0, 1], "f", "n")
    assert rgba == [1.0, 0.0, 0.0, 1.0] and not from_token
    font, from_token = t.font_of("header", "f", "n")
    assert font == {"face": layoutgen.FONT_FACE_DEFAULT, "size": 16.0, "fixed": False} and from_token
    assert t.font_of("field", "f", "n")[0]["fixed"] is True
    assert t.pair("$device.page", "f", "n") == (1306.0, 518.0)
    assert t.pair([640, "$size.contactRow"], "f", "n") == (640.0, 55.0)


@pytest.mark.parametrize("value, what", [
    ("$space.nope", "unknown token"), ("$nope.page", "unknown token"),
    ("fill", "must be a number"), (True, "not a bool"),
])
def test_a_bad_number_names_the_file_the_node_and_the_reason(value, what):
    with pytest.raises(LayoutGenError) as caught:
        tokens().number(value, "ui/x.json", "root.0", "w")
    assert what in str(caught.value) and "ui/x.json root.0" in str(caught.value)


def test_a_bad_color_or_font_token_is_refused():
    with pytest.raises(LayoutGenError, match="unknown color token"):
        tokens().color_of("$mauve", "f", "n")
    with pytest.raises(LayoutGenError, match="unknown font token"):
        tokens().font_of("mono", "f", "n")


def test_tokens_file_is_validated_shape_by_shape():
    with pytest.raises(LayoutGenError, match="color.bad must be four numbers 0..1"):
        Tokens.from_text('{"color": {"bad": [1, 2]}}', "ui/tokens.json")
    with pytest.raises(LayoutGenError, match="font.h must be"):
        Tokens.from_text('{"font": {"h": "big"}}', "ui/tokens.json")
    with pytest.raises(LayoutGenError, match="space.page must be a number"):
        Tokens.from_text('{"space": {"page": "20"}}', "ui/tokens.json")
    with pytest.raises(LayoutGenError, match="do not parse"):
        Tokens.from_text("{", "ui/tokens.json")


from dayz_mcp.layoutgen import build_layout
from dayz_mcp.layoutlint import lint_layout


def page(body, root=None, layout="oz_page", note=""):
    return {"layout": layout, "note": note,
            "root": root or {"frame": {"name": "OZ_Page", "size": [640, 518], "inset": "$space.page"}},
            "body": body}


def build(desc):
    return build_layout(desc, tokens(), "ui/MyMod/oz_page.json", "MyMod/gui/layouts")


def clean(text: str) -> list:
    return [(f.check, f.message) for f in lint_layout(text, "gen.layout")]


def test_a_frame_root_with_one_label_renders_the_vanilla_shape():
    out = build(page({"label": {"name": "Title", "text": "Hello", "font": "header", "color": "$accent",
                                "w": 300, "h": 26}}, note="A page."))
    assert list(out.files) == ["MyMod/gui/layouts/oz_page.layout"]
    text = out.files["MyMod/gui/layouts/oz_page.layout"]
    assert text.splitlines()[0] == "// GENERATED by dayz-mcp layout_build from ui/MyMod/oz_page.json -- edit the source, not this file."
    assert text.splitlines()[1] == "// A page."
    assert text.splitlines()[2] == "FrameWidgetClass OZ_Page {"
    assert (
        "  TextWidgetClass Title {\n"
        "   visible 1\n"
        "   ignorepointer 1\n"
        "   position 20 20\n"
        "   size 300 26\n"
        "   hexactpos 1\n"
        "   vexactpos 1\n"
        "   hexactsize 1\n"
        "   vexactsize 1\n"
        "   color 0.31 0.71 0.91 1\n"
        "   priority 0\n"
        '   text "Hello"\n'
        '   font "gui/fonts/sdf_MetronBook24"\n'
        '   "exact text" 1\n'
        '   "exact text size" 16\n'
        '   "text halign" left\n'
        '   "text valign" center\n'
        "  }\n"
    ) in text
    assert clean(text) == []
    assert out.notes == []


def test_root_props_inset_and_children_offsets():
    out = build(page({"panel": {"name": "Bg", "size": "fill", "color": "$panel"}}))
    text = out.files["MyMod/gui/layouts/oz_page.layout"]
    assert " visible 1\n position 0 0\n size 640 518\n hexactpos 1\n vexactpos 1\n hexactsize 1\n vexactsize 1\n" in text
    # size "fill" at the inner origin is the full inner box, exact
    assert "  PanelWidgetClass Bg {\n   visible 1\n   ignorepointer 1\n   position 20 20\n   size 600 478\n" in text
    assert "   style rover_sim_colorable\n" in text


def test_a_label_can_size_itself_and_anchor_right():
    out = build(page({"label": {"name": "Where", "anchor": "right", "at": [12, 6], "w": "auto", "h": 25,
                                "text": "nearby", "font": "small", "color": "$muted", "align": "right"}}))
    text = out.files["MyMod/gui/layouts/oz_page.layout"]
    assert "   halign right_ref\n   position 32 26\n   size 0 25\n" in text
    assert '   "size to text h" 1\n' in text and '   "text halign" right\n' in text
    assert clean(text) == []


def test_rule_chip_and_hidden_widgets():
    out = build(page({"frame": {"name": "Card", "at": [0, 0], "size": [300, 55], "children": [
        {"chip": {"name": "Chip"}},
        {"rule": {"name": "Line", "anchor": "bottom", "at": [22, 0], "w": "fill"}},
        {"panel": {"name": "Pick", "size": "fill", "color": "$pick", "hidden": True}},
    ]}}))
    text = out.files["MyMod/gui/layouts/oz_page.layout"]
    assert "PanelWidgetClass Chip {\n     visible 0\n     ignorepointer 1\n     position 0 0\n     size 4 1\n     hexactpos 1\n     vexactpos 1\n     hexactsize 1\n     vexactsize 0\n     color 1 1 1 1\n     priority 0\n" in text
    assert "PanelWidgetClass Line {\n     visible 1\n     ignorepointer 1\n     valign bottom_ref\n     position 22 0\n     size 278 1\n" in text
    assert "PanelWidgetClass Pick {\n     visible 0\n" in text and "     priority 2\n" in text
    assert clean(text) == []


def test_at_on_a_page_child_is_noted_but_hidden_overlays_are_not():
    out = build(page({"frame": {"name": "Wrap", "size": [100, 100], "children": [
        {"panel": {"name": "A", "at": [5, 5], "size": [10, 10], "color": "$panel"}},
        {"panel": {"name": "Over", "at": [5, 5], "size": [10, 10], "color": "$panel", "hidden": True}},
    ]}}))
    assert out.notes == []
    out = build(page({"panel": {"name": "Loose", "at": [5, 5], "size": [10, 10], "color": "$panel"}}))
    assert out.notes == ["ui/MyMod/oz_page.json root.0: `at` on a page child -- build the page with vbox/hbox"]


@pytest.mark.parametrize("desc, message", [
    ({"layout": "x", "root": {"frame": {"name": "R", "size": [1, 1]}},
      "body": {"label": {"name": "A", "h": 20}, "panel": {}}}, "exactly one primitive key"),
    ({"layout": "x", "root": {"frame": {"name": "R", "size": [1, 1]}},
      "body": {"sparkle": {"name": "A"}}}, "unknown primitive 'sparkle'"),
    ({"layout": "x", "root": {"frame": {"name": "R", "size": [1, 1]}},
      "body": {"label": {"name": "A", "h": 20, "bold": 1}}}, "label does not take ['bold']"),
    ({"layout": "x", "root": {"frame": {"name": "R", "size": [100, 100]}},
      "body": {"frame": {"name": "F", "size": [50, 50], "children": [
          {"panel": {"name": "Dup", "size": [1, 1], "color": "$panel"}},
          {"panel": {"name": "Dup", "size": [1, 1], "color": "$panel"}}]}}}, "duplicate widget name 'Dup'"),
    ({"layout": "x", "root": {"frame": {"name": "R", "size": [100, 100]}},
      "body": {"label": {"name": "A", "h": 20, "text": 'say "hi"'}}}, "quote inside text"),
    ({"layout": "x", "root": {"label": {"name": "R"}}}, "root must be a frame or a panel"),
    ({"layout": "x", "root": {"frame": {"name": "R"}}}, "root needs an exact size"),
    ({"layout": "x", "root": {"frame": {"name": "R", "size": [100, 100]}},
      "body": {"label": {"name": "A", "h": "auto"}}}, "auto is only a label's width"),
])
def test_refusals_name_the_node(desc, message):
    with pytest.raises(LayoutGenError) as caught:
        build_layout(desc, tokens(), "ui/MyMod/x.json", "MyMod/gui/layouts")
    assert message in str(caught.value) and "ui/MyMod/x.json" in str(caught.value)


def test_literal_colors_and_fonts_are_allowed_but_noted():
    out = build(page({"label": {"name": "A", "h": 20, "color": [1, 0, 0, 1], "font": {"size": 12}}}))
    assert out.notes == [
        "ui/MyMod/oz_page.json root.0: color given as a literal -- use a $color token",
        "ui/MyMod/oz_page.json root.0: font given as a literal -- use a $font token",
    ]


def test_a_gap_keeps_its_anchor():
    out = build(page({"frame": {"name": "Row", "size": [300, 40], "children": [
        {"gap": {"anchor": "right", "at": [10, 0], "w": 20, "h": 5}}]}}))
    text = out.files["MyMod/gui/layouts/oz_page.layout"]
    assert "PanelWidgetClass Gap1 {\n     visible 1\n     ignorepointer 1\n     halign right_ref\n     position 10 0\n     size 20 5\n" in text
    assert clean(text) == []


def test_vbox_places_children_and_resolves_one_fill():
    out = build(page({"vbox": {"gap": "$space.tight", "children": [
        {"label": {"name": "Header", "h": "$size.header", "font": "title", "color": "$accent"}},
        {"panel": {"name": "Body", "h": "fill", "color": "$panel"}},
        {"label": {"name": "Hint", "h": "$size.hint", "font": "hint", "color": "$faint"}},
        {"hbox": {"h": "$size.button", "gap": 30, "children": [
            {"button": {"name": "BtnMsg", "w": "fill", "hidden": True}},
            {"button": {"name": "BtnFriend", "w": "fill"}},
        ]}},
    ]}}))
    text = out.files["MyMod/gui/layouts/oz_page.layout"]
    assert "TextWidgetClass Header {\n   visible 1\n   ignorepointer 1\n   position 20 20\n   size 600 34\n" in text
    # 478 inner - 34 - 22 - 30 - three gaps of 6 = 374
    assert "PanelWidgetClass Body {\n   visible 1\n   ignorepointer 1\n   position 20 60\n   size 600 374\n" in text
    assert "TextWidgetClass Hint {\n   visible 1\n   ignorepointer 1\n   position 20 440\n   size 600 22\n" in text
    assert "ButtonWidgetClass BtnMsg {\n   visible 0\n   position 20 468\n   size 285 30\n" in text
    assert "ButtonWidgetClass BtnFriend {\n   visible 1\n   position 335 468\n   size 285 30\n" in text
    assert clean(text) == [] and out.notes == []


def test_a_named_vbox_is_a_frame_with_relative_children():
    out = build(page({"vbox": {"name": "Column", "w": 300, "h": 100, "children": [
        {"label": {"name": "A", "h": 20}}, {"label": {"name": "B", "h": 20}}]}}))
    text = out.files["MyMod/gui/layouts/oz_page.layout"]
    assert "  FrameWidgetClass Column {\n   visible 1\n   position 20 20\n   size 300 100\n" in text
    assert "    TextWidgetClass A {\n     visible 1\n     ignorepointer 1\n     position 0 0\n     size 300 20\n" in text
    assert "    TextWidgetClass B {\n     visible 1\n     ignorepointer 1\n     position 0 20\n     size 300 20\n" in text


def test_several_fills_share_the_remainder_equally():
    out = build(page({"vbox": {"children": [{"panel": {"name": "A", "h": "fill", "color": "$panel"}},
                                            {"panel": {"name": "B", "h": 78, "color": "$panel"}},
                                            {"panel": {"name": "C", "h": "fill", "color": "$panel"}}]}}))
    text = out.files["MyMod/gui/layouts/oz_page.layout"]
    assert "PanelWidgetClass A {\n   visible 1\n   ignorepointer 1\n   position 20 20\n   size 600 200\n" in text
    assert "PanelWidgetClass C {\n   visible 1\n   ignorepointer 1\n   position 20 298\n   size 600 200\n" in text


@pytest.mark.parametrize("body, message", [
    ({"vbox": {"children": [{"panel": {"name": "A", "h": 400, "color": "$panel"}},
                            {"panel": {"name": "B", "h": 400, "color": "$panel"}}]}}, "does not fit: needs 800, has 478"),
    ({"vbox": {"children": [{"panel": {"name": "A", "at": [1, 1], "h": 40, "color": "$panel"}}]}}, "`at` is not allowed under a vbox/hbox"),
    ({"hbox": {"h": 30, "children": [{"label": {"name": "A", "text": "x"}}]}}, "w is required here"),
    ({"vbox": {"children": [{"text": {"name": "T", "text": "x"}}]}}, "text needs h inside a vbox"),
])
def test_vbox_and_hbox_refusals(body, message):
    with pytest.raises(LayoutGenError, match=message):
        build(page(body))


def test_button_writes_the_edge_bg_text_idiom():
    out = build(page({"button": {"name": "BtnHide", "size": [195, 30], "text": "#STR_HIDE", "font": "small"}}))
    text = out.files["MyMod/gui/layouts/oz_page.layout"]
    assert (
        "  ButtonWidgetClass BtnHide {\n   visible 1\n   position 20 20\n   size 195 30\n"
        "   hexactpos 1\n   vexactpos 1\n   hexactsize 1\n   vexactsize 1\n   text \"\"\n   priority 0\n   {\n"
        "    PanelWidgetClass BtnHideEdge {\n     visible 1\n     ignorepointer 1\n     position -1 -1\n     size 197 32\n"
    ) in text
    assert "    PanelWidgetClass BtnHideBg {\n     visible 1\n     ignorepointer 1\n     position 0 0\n     size 195 30\n" in text
    assert "     color 0.135 0.18 0.225 1\n     priority 1\n" in text
    assert "    TextWidgetClass BtnHideText {\n     visible 1\n     ignorepointer 1\n     position 0 0\n     size 195 30\n" in text
    assert '     text "#STR_HIDE"\n' in text and '     "text halign" center\n' in text
    assert clean(text) == []


def test_field_puts_the_edit_box_inside_a_frame_and_a_fill():
    out = build(page({"field": {"name": "ChatInput", "size": [472, 28]}}))
    text = out.files["MyMod/gui/layouts/oz_page.layout"]
    assert "  PanelWidgetClass ChatInputFrame {\n   visible 1\n   position 20 20\n   size 472 28\n" in text
    assert "    PanelWidgetClass ChatInputFill {\n     visible 1\n     ignorepointer 1\n     position 1 1\n     size 470 26\n" in text
    assert "    EditBoxWidgetClass ChatInput {\n     visible 1\n     position 6 0\n     size 460 28\n" in text
    assert "     style Default\n" in text and '     font "gui/fonts/MetronBook14"\n' in text
    assert '"exact text size"' not in text.split("EditBoxWidgetClass ChatInput")[1]
    assert clean(text) == []
    out = build(page({"field": {"name": "Body", "size": [400, 200], "lines": 8}}))
    assert "MultilineEditBoxWidgetClass Body {" in out.files["MyMod/gui/layouts/oz_page.layout"]
    assert "     lines 8\n" in out.files["MyMod/gui/layouts/oz_page.layout"]


def test_text_wraps_and_sizes_its_height_to_the_text():
    out = build(page({"text": {"name": "Story", "w": 400, "text": "long", "font": "body"}}))
    text = out.files["MyMod/gui/layouts/oz_page.layout"]
    assert "  RichTextWidgetClass Story {\n   visible 1\n   ignorepointer 1\n   position 20 20\n   size 400 20\n" in text
    assert '   wrap 1\n   "size to text h" 0\n   "size to text v" 1\n' in text
    out = build(page({"text": {"name": "Plain", "w": 400, "plain": True}}))
    assert "MultilineTextWidgetClass Plain {" in out.files["MyMod/gui/layouts/oz_page.layout"]


def test_section_writes_bar_label_and_rule():
    out = build(page({"section": {"name": "SecSpZ", "w": 560, "text": "#STR_SPAWNS"}}))
    text = out.files["MyMod/gui/layouts/oz_page.layout"]
    assert "PanelWidgetClass SecSpZBar {\n   visible 1\n   ignorepointer 1\n   position 20 24\n   size 3 16\n" in text
    assert "TextWidgetClass SecSpZLbl {\n   visible 1\n   ignorepointer 1\n   position 32 20\n   size 548 24\n" in text
    assert "PanelWidgetClass SecSpZRule {\n   visible 1\n   ignorepointer 1\n   position 20 49\n   size 560 1\n" in text
    assert clean(text) == []


CONTACT_LIST = {"list": {"name": "ContactScroll", "stack": "ContactList", "size": [600, 395], "rows": {
    "oz_pda_contact_row": {"row": {"name": "OZ_ContactRow", "h": "$size.contactRow", "click": True,
        "note": "One contact.", "children": [
        {"panel": {"name": "RowBg", "size": "fill", "color": "$panel"}},
        {"panel": {"name": "RowPick", "size": "fill", "color": "$pick", "hidden": True}},
        {"chip": {"name": "RowChip"}},
        {"label": {"name": "RowName", "at": [22, 6], "size": [300, 25], "font": "header"}},
        {"label": {"name": "RowWhere", "anchor": "right", "at": [12, 6], "w": "auto", "h": 25, "font": "small", "color": "$muted", "align": "right"}},
        {"label": {"name": "RowDetail", "at": [22, 30], "w": "fill", "h": 20, "font": "small", "color": "$muted"}},
        {"rule": {"name": "RowLine", "anchor": "bottom", "at": [22, 0], "w": "fill"}},
    ]}}}}}


def test_list_writes_scroll_spacer_and_a_row_file_of_the_scroll_width_minus_the_bar():
    out = build(page(CONTACT_LIST))
    page_text = out.files["MyMod/gui/layouts/oz_page.layout"]
    assert (
        "  ScrollWidgetClass ContactScroll {\n   visible 1\n   position 20 20\n   size 600 395\n"
        "   hexactpos 1\n   vexactpos 1\n   hexactsize 1\n   vexactsize 1\n   priority 0\n   clipchildren 1\n"
        '   "Scrollbar V" 1\n   {\n'
        "    WrapSpacerWidgetClass ContactList {\n     visible 1\n     position 0 0\n     size 1 0\n"
        "     hexactpos 1\n     vexactpos 1\n     hexactsize 0\n     vexactsize 1\n     priority 0\n"
        '     Padding 0\n     Margin 0\n     "Size To Content V" 1\n    }\n'
    ) in page_text
    row = out.files["MyMod/gui/layouts/oz_pda_contact_row.layout"]
    assert row.splitlines()[0] == "// GENERATED by dayz-mcp layout_build from ui/MyMod/oz_page.json (rows.oz_pda_contact_row) -- edit the source, not this file."
    assert row.splitlines()[1] == "// One contact."
    assert "ButtonWidgetClass OZ_ContactRow {\n visible 1\n position 0 0\n size 1 55\n hexactpos 1\n vexactpos 1\n hexactsize 0\n vexactsize 1\n text \"\"\n" in row
    assert "  PanelWidgetClass RowBg {\n   visible 1\n   ignorepointer 1\n   position 0 0\n   size 1 1\n   hexactpos 1\n   vexactpos 1\n   hexactsize 0\n   vexactsize 0\n" in row
    assert "  PanelWidgetClass RowChip {\n   visible 0\n   ignorepointer 1\n   position 0 0\n   size 4 1\n" in row
    # 600 - 10 for the bar = 590 wide; fill from x = 22 is 568
    assert "  TextWidgetClass RowDetail {\n   visible 1\n   ignorepointer 1\n   position 22 30\n   size 568 20\n" in row
    assert "  TextWidgetClass RowWhere {\n   visible 1\n   ignorepointer 1\n   halign right_ref\n   position 12 6\n   size 0 25\n" in row
    assert "  PanelWidgetClass RowLine {\n   visible 1\n   ignorepointer 1\n   valign bottom_ref\n   position 22 0\n   size 568 1\n" in row
    assert clean(page_text) == [] and clean(row) == []


CHAT_LINE = {"row": {"name": "OZ_ChatLine", "stack": True, "children": [
    {"hrow": {"h": 22, "children": [
        {"panel": {"name": "LineMine", "w": 2, "h": 16, "color": "$accent", "hidden": True}},
        {"gap": {"w": 8}},
        {"label": {"name": "LineWho", "w": "auto", "font": "small", "color": "$accent"}},
        {"gap": {"w": 10}},
        {"label": {"name": "LineAt", "w": "auto", "font": "small", "color": "$faint"}},
    ]}},
    {"text": {"name": "LineText", "font": "body"}},
    {"gap": {"h": 8}},
]}}


def test_a_stack_row_lets_the_engine_size_it_from_its_text():
    out = build(page({"list": {"name": "ChatScroll", "stack": "ChatLines", "size": [871, 342],
                               "rows": {"oz_pda_chat_line": CHAT_LINE}}}))
    row = out.files["MyMod/gui/layouts/oz_pda_chat_line.layout"]
    assert (
        "WrapSpacerWidgetClass OZ_ChatLine {\n visible 1\n position 0 0\n size 1 0\n hexactpos 1\n vexactpos 1\n"
        ' hexactsize 0\n vexactsize 1\n Padding 0\n Margin 0\n "Size To Content V" 1\n {\n'
    ) in row
    # the hrow is a GridSpacer that sizes itself; a hidden marker, gaps as panels, self-sized labels
    assert (
        "  GridSpacerWidgetClass HRow1 {\n   visible 1\n   position 0 0\n   size 0 0\n   hexactpos 1\n   vexactpos 1\n"
        '   hexactsize 1\n   vexactsize 1\n   priority 0\n   Padding 0\n   Margin 0\n   "Size To Content H" 1\n'
        '   "Size To Content V" 1\n   Columns 5\n   Rows 1\n'
    ) in row
    assert "    PanelWidgetClass LineMine {\n     visible 0\n     ignorepointer 1\n     position 0 0\n     size 2 16\n" in row
    assert "    PanelWidgetClass Gap1 {\n     visible 1\n     ignorepointer 1\n     position 0 0\n     size 8 22\n" in row
    assert "    TextWidgetClass LineWho {\n     visible 1\n     ignorepointer 1\n     position 0 0\n     size 0 22\n" in row
    assert '     "size to text h" 1\n' in row
    assert "  RichTextWidgetClass LineText {\n   visible 1\n   ignorepointer 1\n   position 0 0\n   size 1 20\n   hexactpos 1\n   vexactpos 1\n   hexactsize 0\n   vexactsize 1\n" in row
    assert '   "size to text v" 1\n' in row
    # Gap1/Gap2 are the hrow's own w:8/w:10 gaps (ctx's gap counter is one
    # sequence, depth-first); this row's own h:8 gap is the third to claim a name.
    assert "  PanelWidgetClass Gap3 {\n   visible 1\n   ignorepointer 1\n   position 0 0\n   size 1 8\n   hexactpos 1\n   vexactpos 1\n   hexactsize 0\n   vexactsize 1\n" in row
    assert clean(row) == []


def test_a_static_stack_and_a_grid_write_exact_numbers():
    out = build(page({"vbox": {"children": [
        {"stack": {"name": "Notes", "h": 100, "children": [
            {"label": {"name": "L1", "h": 20}}, {"text": {"name": "T1"}}]}},
        {"grid": {"name": "Pad", "size": [184, 154], "cols": 3, "rows": 4, "gap": 4, "children": [
            {"panel": {"name": "K1", "color": "$raised"}}, {"panel": {"name": "K2", "color": "$raised"}}]}},
    ]}}))
    text = out.files["MyMod/gui/layouts/oz_page.layout"]
    assert "  WrapSpacerWidgetClass Notes {\n   visible 1\n   position 20 20\n   size 600 0\n   hexactpos 1\n   vexactpos 1\n   hexactsize 1\n   vexactsize 1\n" in text
    assert "    TextWidgetClass L1 {\n     visible 1\n     ignorepointer 1\n     position 0 0\n     size 600 20\n" in text
    assert "    RichTextWidgetClass T1 {\n     visible 1\n     ignorepointer 1\n     position 0 0\n     size 600 20\n" in text
    assert "  GridSpacerWidgetClass Pad {\n   visible 1\n   position 20 120\n   size 184 154\n" in text
    assert "   Padding 4\n   Margin 0\n   Columns 3\n   Rows 4\n" in text
    # cells: (184 - 2*4)/3 = 58.667 by (154 - 3*4)/4 = 35.5
    assert "    PanelWidgetClass K1 {\n     visible 1\n     ignorepointer 1\n     position 0 0\n     size 58.667 35.5\n" in text
    assert clean(text) == []


def test_keypad_is_a_grid_of_glyph_buttons():
    out = build(page({"keypad": {"name": "LockPad", "at": [0, 40], "anchor": "center", "size": [184, 154],
                                 "cols": 3, "rows": 4, "gap": 4,
                                 "keys": [{"name": "Key1", "glyph": "1"}, {"name": "Key2", "glyph": "2"}]}}))
    text = out.files["MyMod/gui/layouts/oz_page.layout"]
    assert "  GridSpacerWidgetClass LockPad {\n   visible 1\n   halign center_ref\n   valign center_ref\n   position 0 40\n   size 184 154\n" in text
    assert "    ButtonWidgetClass Key1 {\n     visible 1\n     position 0 0\n     size 58.667 35.5\n" in text
    assert "      TextWidgetClass Key1Text {" in text and '       text "1"\n' in text
    assert clean(text) == []


def test_listbox_and_raw_pass_their_properties_through():
    out = build(page({"listbox": {"name": "InviteList", "size": [851, 295], "font": "hint",
                                  "props": {"style": "NoScrollBar", "title visible": 0, "highlight row": 1, "lines": 14,
                                            "colums": "Name;70;Faction;30"}}}))
    text = out.files["MyMod/gui/layouts/oz_page.layout"]
    assert "  TextListboxWidgetClass InviteList {\n   visible 1\n   position 20 20\n   size 851 295\n" in text
    assert '   style NoScrollBar\n   "title visible" 0\n   "highlight row" 1\n   lines 14\n   colums "Name;70;Faction;30"\n' in text
    assert '   font "gui/fonts/sdf_MetronBook24"\n   "exact text" 1\n   "exact text size" 14\n' in text
    out = build(page({"raw": {"name": "Map", "class": "MapWidgetClass", "size": "fill", "props": {"filter": 1}}}))
    assert "  MapWidgetClass Map {\n   visible 1\n   position 20 20\n   size 600 478\n" in out.files["MyMod/gui/layouts/oz_page.layout"]
    assert clean(text) == []


def test_a_preview_under_a_high_priority_is_refused():
    with pytest.raises(LayoutGenError, match="priority 300 above 256 on the way to the preview"):
        build(page({"frame": {"name": "Card", "size": [300, 300], "priority": 300, "children": [
            {"preview": {"name": "ItemView", "size": [200, 200]}}]}}))
    out = build(page({"preview": {"name": "ItemView", "size": [200, 200], "priority": 256}}))
    assert "  ItemPreviewWidgetClass ItemView {\n   visible 1\n   position 20 20\n   size 200 200\n" in out.files["MyMod/gui/layouts/oz_page.layout"]


def test_stack_children_may_not_fill():
    with pytest.raises(LayoutGenError, match="a stack child cannot fill"):
        build(page({"stack": {"name": "S", "h": 100, "children": [{"panel": {"name": "P", "size": "fill", "color": "$panel"}}]}}))


def test_everything_generated_in_this_file_is_lint_clean():
    """Every golden case above, in one sweep: the generator's contract."""
    pages = [page(CONTACT_LIST), page({"list": {"name": "S", "stack": "L", "size": [871, 342], "rows": {"r": CHAT_LINE}}}),
             page({"button": {"name": "B", "size": [100, 30]}}), page({"field": {"name": "F", "size": [200, 28]}})]
    for desc in pages:
        for path, text in build(desc).files.items():
            assert clean(text) == [], path


from pathlib import Path

from dayz_mcp.layoutgen import build_project

PAGE = {"layout": "oz_page", "root": {"frame": {"name": "OZ_Page", "size": [640, 518], "inset": 20}},
        "body": {"label": {"name": "Title", "h": 30, "text": "Hello"}}}


def project(tmp_path: Path) -> Path:
    (tmp_path / "ui").mkdir()
    (tmp_path / "ui" / "tokens.json").write_text(json.dumps(TOKENS), encoding="utf-8")
    (tmp_path / "ui" / "MyMod").mkdir()
    (tmp_path / "ui" / "MyMod" / "oz_page.json").write_text(json.dumps(PAGE), encoding="utf-8")
    (tmp_path / "MyMod").mkdir()
    return tmp_path


def test_build_project_writes_changed_files_only(tmp_path):
    root = project(tmp_path)
    first = build_project(root, ["MyMod"], {}, write=True)
    assert first.written == ["MyMod/gui/layouts/oz_page.layout"] and first.unchanged == []
    out = root / "MyMod" / "gui" / "layouts" / "oz_page.layout"
    assert out.read_text(encoding="utf-8").startswith("// GENERATED by dayz-mcp layout_build from ui/MyMod/oz_page.json")
    assert b"\r\n" not in out.read_bytes()
    second = build_project(root, ["MyMod"], {}, write=True)
    assert second.written == [] and second.unchanged == ["MyMod/gui/layouts/oz_page.layout"]
    assert second.sources == {"MyMod/gui/layouts/oz_page.layout": "ui/MyMod/oz_page.json"}


def test_build_project_with_write_false_reports_but_touches_nothing(tmp_path):
    root = project(tmp_path)
    report = build_project(root, ["MyMod"], {}, write=False)
    assert report.written == ["MyMod/gui/layouts/oz_page.layout"]
    assert not (root / "MyMod" / "gui").exists()


def test_build_project_without_a_ui_folder_is_a_quiet_no_op(tmp_path):
    (tmp_path / "MyMod").mkdir()
    report = build_project(tmp_path, ["MyMod"], {}, write=True)
    assert report.written == [] and report.files == {}


def test_build_project_refuses_a_bad_description_before_writing_anything(tmp_path):
    root = project(tmp_path)
    (root / "ui" / "MyMod" / "bad.json").write_text('{"layout": "bad", "root": {"label": {}}}', encoding="utf-8")
    with pytest.raises(LayoutGenError, match="ui/MyMod/bad.json root: root must be a frame or a panel"):
        build_project(root, ["MyMod"], {}, write=True)
    assert not (root / "MyMod" / "gui").exists()


def test_build_project_refuses_two_descriptions_for_one_file(tmp_path):
    root = project(tmp_path)
    (root / "ui" / "MyMod" / "twin.json").write_text(json.dumps(PAGE), encoding="utf-8")
    with pytest.raises(LayoutGenError, match="oz_page.layout is generated by two descriptions"):
        build_project(root, ["MyMod"], {}, write=True)


def test_build_project_needs_tokens_once_a_ui_folder_exists(tmp_path):
    root = project(tmp_path)
    (root / "ui" / "tokens.json").unlink()
    with pytest.raises(LayoutGenError, match="ui/tokens.json is missing"):
        build_project(root, ["MyMod"], {}, write=True)


def test_main_refuses_an_unknown_mod_and_builds_a_known_one(tmp_path, capsys):
    root = project(tmp_path)
    (root / "dayz-mcp.toml").write_text('[project]\nname = "my-mod"\n\n[build]\nmods = ["MyMod"]\n', encoding="utf-8")
    (root / "MyMod" / "config.cpp").write_text("class CfgPatches { };\n", encoding="utf-8")
    assert layoutgen.main([str(root), "Other"]) == 1
    assert "'Other' is not a mod of this project; it declares: MyMod" in capsys.readouterr().out
    assert not (root / "MyMod" / "gui").exists()
    assert layoutgen.main([str(root), "MyMod"]) == 0
    assert "wrote MyMod/gui/layouts/oz_page.layout" in capsys.readouterr().out
    assert layoutgen.main([]) == 2
